/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        palette: {
          'white-bright': '#fcfbf3',
          'white-pure': '#ffffff',
          'black-pure': '#000000',
          'slate-darkest': '#2a152d',
          'slate-dark': '#34404f',
          'slate-medium': '#4a4b5b',
          'slate-light': '#707b89',
          'slate-lighter': '#a9bcbf',
          'slate-lightest': '#e6eeed',
          'red-bright': '#ff5555',
          'red-dark': '#813645',
          'red-medium': '#9d4343',
          'red-muted': '#c06852',
          'blue-bright': '#7fbbdc',
          'blue-dark': '#3e4c7e',
          'blue-medium': '#495f94',
          'blue-light': '#5a78b2',
          'blue-info': '#7396d5',
          'blue-cyan': '#7fbbdc',
          'blue-cyan-light': '#aaeeea',
          'green-success': '#96dc7f',
          'green-health': '#6ec077',
          'green-lime': '#d5f893',
          'yellow-bright': '#fceba8',
          'yellow-medium': '#f5c47c',
          'orange-medium': '#e39764',
          'purple-dark': '#542240',
          'purple-medium': '#794e6d',
          'purple-bright': '#8877ff',
          'purple-bright-dark': '#4433aa',
          'ground-dark': '#2e2e43',
          'ground-medium': '#313148',
          'ground-shadow': '#3e3f4d',
          'ground-highlight': '#565769',
          'purple-void': '#241227',
        },
        ui: {
          'text-primary': '#fcfbf3',
          'text-secondary': '#e6eeed',
          'text-muted': '#a9bcbf',
          'text-dim': '#707b89',
          'background-dark': '#34404f',
          'background-darkest': '#2a152d',
          'white': '#ffffff',
          'black': '#000000',
          'team-red-dark': '#813645',
          'team-red-medium': '#9d4343',
          'team-blue-dark': '#3e4c7e',
          'team-blue-medium': '#495f94',
          'label-yellow': '#f5c47c',
          'separator': '#4a4b5b',
        },
        game: {
          'team-red-bright': '#ff5555',
          'team-blue-bright': '#7fbbdc',
        },
        terminal: {
          'background': '#241227',
          'border': '#4a4b5b',
          'text-default': '#e6eeed',
          'text-muted': '#a9bcbf',
          'text-dim': '#707b89',
          'prompt': '#96dc7f',
          'success': '#707b89',
          'info': '#7fbbdc',
          'warning': '#fceba8',
          'error': '#c06852',
          'command': '#7fbbdc',
          'argument': '#d5f893',
          'value': '#fceba8',
        },
        primary: '#ff0099',
        'primary-hover': '#d4007f',
        secondary: '#00f0ff',
        accent: '#ffe600',
        'background-base': '#2e2e43',
        'card-dark': '#232334',
        'border-dark': '#42425a',
        'terminal-bg': '#1e1e2e',
        'code-bg': '#151520',
      },
      fontFamily: {
        display: ['Space Grotesk', 'sans-serif'],
        mono: ['JetBrains Mono', 'Fira Code', 'monospace'],
      },
      backgroundImage: {
        'grid-pattern': 'linear-gradient(to right, #42425a 1px, transparent 1px), linear-gradient(to bottom, #42425a 1px, transparent 1px)',
      },
    },
  },
  plugins: [],
}
