// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

// The tagged union or sum type for the algebraic type `AiBehavior`.
const AiBehavior = __t.enum("AiBehavior", {None: __t.unit(),
  GameAI: __t.unit(),
  Tilebound: __t.unit(),
  RandomAim: __t.unit(),
  Turret: __t.unit(),
  TargetBot: __t.unit(),
  AimBot: __t.unit(),
});

export default AiBehavior;


