// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import BaseTerrain from "./base_terrain_type";


export default __t.row({
  gameId: __t.string().primaryKey(),
  get layer() {
    return __t.array(BaseTerrain);
  },
  width: __t.i32(),
  height: __t.i32(),
});
