// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import WorldVisibility from "./world_visibility_type";

export default {
  joinCode: __t.string(),
  get visibility() {
    return WorldVisibility;
  },
  botCount: __t.i32(),
  gameDurationMicros: __t.i64(),
  width: __t.i32(),
  height: __t.i32(),
};
