// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import DecorationType from "./decoration_type_type";


export default __t.object("Decoration", {
  id: __t.string(),
  worldId: __t.string(),
  positionX: __t.f32(),
  positionY: __t.f32(),
  gridX: __t.i32(),
  gridY: __t.i32(),
  get type() {
    return DecorationType;
  },
});


