// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  GameVisibility,
  GameState,
  GameType,
} from "./types";


export default __t.row({
  id: __t.string().primaryKey(),
  createdAt: __t.u64().name("created_at"),
  width: __t.i32(),
  height: __t.i32(),
  get gameState() {
    return GameState.name("game_state");
  },
  get gameType() {
    return GameType.name("game_type");
  },
  gameStartedAt: __t.u64().name("game_started_at"),
  gameDurationMicros: __t.i64().name("game_duration_micros"),
  get visibility() {
    return GameVisibility;
  },
  maxPlayers: __t.i32().name("max_players"),
  currentPlayerCount: __t.i32().name("current_player_count"),
  botCount: __t.i32().name("bot_count"),
  minPlayersPerTeam: __t.i32().name("min_players_per_team"),
  owner: __t.option(__t.identity()),
});
