// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import GameVisibility from "./game_visibility_type";
import GameState from "./game_state_type";
import GameType from "./game_type_type";


export default __t.row({
  id: __t.string().primaryKey(),
  createdAt: __t.u64(),
  width: __t.i32(),
  height: __t.i32(),
  get gameState() {
    return GameState;
  },
  get gameType() {
    return GameType;
  },
  gameStartedAt: __t.u64(),
  gameDurationMicros: __t.i64(),
  get visibility() {
    return GameVisibility;
  },
  maxPlayers: __t.i32(),
  currentPlayerCount: __t.i32(),
  botCount: __t.i32(),
  minPlayersPerTeam: __t.i32(),
  owner: __t.option(__t.identity()),
});
