// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import GameVisibility from "./game_visibility_type";
import BaseTerrain from "./base_terrain_type";
import GameState from "./game_state_type";


export default __t.row({
  id: __t.string().primaryKey().name("Id"),
  createdAt: __t.u64().name("CreatedAt"),
  width: __t.i32().name("Width"),
  height: __t.i32().name("Height"),
  get baseTerrainLayer() {
    return __t.array(BaseTerrain).name("BaseTerrainLayer");
  },
  get gameState() {
    return GameState.name("GameState");
  },
  isHomeGame: __t.bool().name("IsHomeGame"),
  gameStartedAt: __t.u64().name("GameStartedAt"),
  gameDurationMicros: __t.i64().name("GameDurationMicros"),
  get visibility() {
    return GameVisibility.name("Visibility");
  },
  maxPlayers: __t.i32().name("MaxPlayers"),
  currentPlayerCount: __t.i32().name("CurrentPlayerCount"),
  botCount: __t.i32().name("BotCount"),
  owner: __t.option(__t.identity()).name("Owner"),
});
