// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

// The tagged union or sum type for the algebraic type `GunType`.
const GunType = __t.enum("GunType", {Base: __t.unit(),
  TripleShooter: __t.unit(),
  MissileLauncher: __t.unit(),
  Boomerang: __t.unit(),
  Grenade: __t.unit(),
});

export default GunType;


