// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import ProjectileType from "./projectile_type_type";
import ExplosionTrigger from "./explosion_trigger_type";
import GunType from "./gun_type_type";


export default __t.object("Gun", {
  get gunType() {
    return GunType;
  },
  ammo: __t.option(__t.i32()),
  projectileCount: __t.i32(),
  spreadAngle: __t.f32(),
  damage: __t.i32(),
  trackingStrength: __t.f32(),
  trackingRadius: __t.f32(),
  get projectileType() {
    return ProjectileType;
  },
  lifetimeSeconds: __t.f32(),
  maxCollisions: __t.i32(),
  passThroughTerrain: __t.bool(),
  collisionRadius: __t.f32(),
  explosionRadius: __t.option(__t.f32()),
  get explosionTrigger() {
    return ExplosionTrigger;
  },
  damping: __t.option(__t.f32()),
  bounce: __t.bool(),
  projectileSize: __t.f32(),
});


