// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.10.0 (commit 1d576dc75ca066879f6d9ee4d156c5bce940bd31).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  convertToAccessorMap as __convertToAccessorMap,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import and reexport all reducer arg types
import Aim from "./aim_reducer";
export { Aim };
import ChangeName from "./change_name_reducer";
export { ChangeName };
import CheckAndRespawnEnemyTanks from "./check_and_respawn_enemy_tanks_reducer";
export { CheckAndRespawnEnemyTanks };
import CleanupResultsGames from "./cleanup_results_games_reducer";
export { CleanupResultsGames };
import CreateGame from "./create_game_reducer";
export { CreateGame };
import DeleteKill from "./delete_kill_reducer";
export { DeleteKill };
import Drive from "./drive_reducer";
export { Drive };
import EndGame from "./end_game_reducer";
export { EndGame };
import EnsureHomegame from "./ensure_homegame_reducer";
export { EnsureHomegame };
import ExitGame from "./exit_game_reducer";
export { ExitGame };
import Fire from "./fire_reducer";
export { Fire };
import HandleConnect from "./handle_connect_reducer";
export { HandleConnect };
import HandleDisconnect from "./handle_disconnect_reducer";
export { HandleDisconnect };
import HomeWorldProjectileExpire from "./home_world_projectile_expire_reducer";
export { HomeWorldProjectileExpire };
import HomeWorldProjectileTankHit from "./home_world_projectile_tank_hit_reducer";
export { HomeWorldProjectileTankHit };
import HomeWorldProjectileTerrainHit from "./home_world_projectile_terrain_hit_reducer";
export { HomeWorldProjectileTerrainHit };
import JoinGame from "./join_game_reducer";
export { JoinGame };
import Ping from "./ping_reducer";
export { Ping };
import ResetGame from "./reset_game_reducer";
export { ResetGame };
import Respawn from "./respawn_reducer";
export { Respawn };
import SpawnPickup from "./spawn_pickup_reducer";
export { SpawnPickup };
import Stop from "./stop_reducer";
export { Stop };
import SwitchGun from "./switch_gun_reducer";
export { SwitchGun };
import Track from "./track_reducer";
export { Track };
import UpdateAi from "./update_ai_reducer";
export { UpdateAi };
import UpdateProjectiles from "./update_projectiles_reducer";
export { UpdateProjectiles };
import UpdateTanks from "./update_tanks_reducer";
export { UpdateTanks };

// Import and reexport all procedure arg types

// Import and reexport all table handle types
import ScheduledAiUpdateRow from "./scheduled_ai_update_table";
export { ScheduledAiUpdateRow };
import ScheduledEnemyTankRespawnCheckRow from "./scheduled_enemy_tank_respawn_check_table";
export { ScheduledEnemyTankRespawnCheckRow };
import ScheduledGameCleanupRow from "./scheduled_game_cleanup_table";
export { ScheduledGameCleanupRow };
import ScheduledGameEndRow from "./scheduled_game_end_table";
export { ScheduledGameEndRow };
import ScheduledGameResetRow from "./scheduled_game_reset_table";
export { ScheduledGameResetRow };
import ScheduledPickupSpawnRow from "./scheduled_pickup_spawn_table";
export { ScheduledPickupSpawnRow };
import ScheduledProjectileUpdatesRow from "./scheduled_projectile_updates_table";
export { ScheduledProjectileUpdatesRow };
import ScheduledTankUpdatesRow from "./scheduled_tank_updates_table";
export { ScheduledTankUpdatesRow };
import GameRow from "./game_table";
export { GameRow };
import KillsRow from "./kills_table";
export { KillsRow };
import PickupRow from "./pickup_table";
export { PickupRow };
import PlayerRow from "./player_table";
export { PlayerRow };
import ProjectileRow from "./projectile_table";
export { ProjectileRow };
import ProjectileTransformRow from "./projectile_transform_table";
export { ProjectileTransformRow };
import ScoreRow from "./score_table";
export { ScoreRow };
import TankRow from "./tank_table";
export { TankRow };
import TankFireStateRow from "./tank_fire_state_table";
export { TankFireStateRow };
import TankPathRow from "./tank_path_table";
export { TankPathRow };
import TankTransformRow from "./tank_transform_table";
export { TankTransformRow };
import TerrainDetailRow from "./terrain_detail_table";
export { TerrainDetailRow };
import TraversibilityMapRow from "./traversibility_map_table";
export { TraversibilityMapRow };

// Import and reexport all types
import AiBehavior from "./ai_behavior_type";
export { AiBehavior };
import AiConfig from "./ai_config_type";
export { AiConfig };
import BaseTerrain from "./base_terrain_type";
export { BaseTerrain };
import DamagedTank from "./damaged_tank_type";
export { DamagedTank };
import DamagedTile from "./damaged_tile_type";
export { DamagedTile };
import ExplosionTrigger from "./explosion_trigger_type";
export { ExplosionTrigger };
import Game from "./game_type";
export { Game };
import GameState from "./game_state_type";
export { GameState };
import GameVisibility from "./game_visibility_type";
export { GameVisibility };
import Gun from "./gun_type";
export { Gun };
import GunType from "./gun_type_type";
export { GunType };
import Kill from "./kill_type";
export { Kill };
import Pickup from "./pickup_type";
export { Pickup };
import PickupType from "./pickup_type_type";
export { PickupType };
import Player from "./player_type";
export { Player };
import Projectile from "./projectile_type";
export { Projectile };
import ProjectileTransform from "./projectile_transform_type";
export { ProjectileTransform };
import ProjectileType from "./projectile_type_type";
export { ProjectileType };
import ScheduledAiUpdate from "./scheduled_ai_update_type";
export { ScheduledAiUpdate };
import ScheduledEnemyTankRespawnCheck from "./scheduled_enemy_tank_respawn_check_type";
export { ScheduledEnemyTankRespawnCheck };
import ScheduledGameCleanup from "./scheduled_game_cleanup_type";
export { ScheduledGameCleanup };
import ScheduledGameEnd from "./scheduled_game_end_type";
export { ScheduledGameEnd };
import ScheduledGameReset from "./scheduled_game_reset_type";
export { ScheduledGameReset };
import ScheduledPickupSpawn from "./scheduled_pickup_spawn_type";
export { ScheduledPickupSpawn };
import ScheduledProjectileUpdates from "./scheduled_projectile_updates_type";
export { ScheduledProjectileUpdates };
import ScheduledTankUpdates from "./scheduled_tank_updates_type";
export { ScheduledTankUpdates };
import Score from "./score_type";
export { Score };
import Tank from "./tank_type";
export { Tank };
import TankFireState from "./tank_fire_state_type";
export { TankFireState };
import TankPath from "./tank_path_type";
export { TankPath };
import TankTransform from "./tank_transform_type";
export { TankTransform };
import TerrainDetail from "./terrain_detail_type";
export { TerrainDetail };
import TerrainDetailType from "./terrain_detail_type_type";
export { TerrainDetailType };
import TraversibilityMap from "./traversibility_map_type";
export { TraversibilityMap };
import Vector2Float from "./vector_2_float_type";
export { Vector2Float };

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema(
  __table({
    name: 'ScheduledAIUpdate',
    indexes: [
      { name: 'GameId', algorithm: 'btree', columns: [
        'gameId',
      ] },
      { name: 'ScheduledId', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
    ],
    constraints: [
      { name: 'ScheduledAIUpdate_ScheduledId_key', constraint: 'unique', columns: ['scheduledId'] },
    ],
  }, ScheduledAiUpdateRow),
  __table({
    name: 'ScheduledEnemyTankRespawnCheck',
    indexes: [
      { name: 'GameId', algorithm: 'btree', columns: [
        'gameId',
      ] },
      { name: 'ScheduledId', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
    ],
    constraints: [
      { name: 'ScheduledEnemyTankRespawnCheck_ScheduledId_key', constraint: 'unique', columns: ['scheduledId'] },
    ],
  }, ScheduledEnemyTankRespawnCheckRow),
  __table({
    name: 'ScheduledGameCleanup',
    indexes: [
      { name: 'ScheduledId', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
    ],
    constraints: [
      { name: 'ScheduledGameCleanup_ScheduledId_key', constraint: 'unique', columns: ['scheduledId'] },
    ],
  }, ScheduledGameCleanupRow),
  __table({
    name: 'ScheduledGameEnd',
    indexes: [
      { name: 'GameId', algorithm: 'btree', columns: [
        'gameId',
      ] },
      { name: 'ScheduledId', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
    ],
    constraints: [
      { name: 'ScheduledGameEnd_ScheduledId_key', constraint: 'unique', columns: ['scheduledId'] },
    ],
  }, ScheduledGameEndRow),
  __table({
    name: 'ScheduledGameReset',
    indexes: [
      { name: 'GameId', algorithm: 'btree', columns: [
        'gameId',
      ] },
      { name: 'ScheduledId', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
    ],
    constraints: [
      { name: 'ScheduledGameReset_ScheduledId_key', constraint: 'unique', columns: ['scheduledId'] },
    ],
  }, ScheduledGameResetRow),
  __table({
    name: 'ScheduledPickupSpawn',
    indexes: [
      { name: 'GameId', algorithm: 'btree', columns: [
        'gameId',
      ] },
      { name: 'ScheduledId', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
    ],
    constraints: [
      { name: 'ScheduledPickupSpawn_ScheduledId_key', constraint: 'unique', columns: ['scheduledId'] },
    ],
  }, ScheduledPickupSpawnRow),
  __table({
    name: 'ScheduledProjectileUpdates',
    indexes: [
      { name: 'GameId', algorithm: 'btree', columns: [
        'gameId',
      ] },
      { name: 'ScheduledId', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
    ],
    constraints: [
      { name: 'ScheduledProjectileUpdates_ScheduledId_key', constraint: 'unique', columns: ['scheduledId'] },
    ],
  }, ScheduledProjectileUpdatesRow),
  __table({
    name: 'ScheduledTankUpdates',
    indexes: [
      { name: 'GameId', algorithm: 'btree', columns: [
        'gameId',
      ] },
      { name: 'ScheduledId', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
    ],
    constraints: [
      { name: 'ScheduledTankUpdates_ScheduledId_key', constraint: 'unique', columns: ['scheduledId'] },
    ],
  }, ScheduledTankUpdatesRow),
  __table({
    name: 'game',
    indexes: [
      { name: 'GameState_IsHomeGame_Visibility', algorithm: 'btree', columns: [
        'gameState',
        'isHomeGame',
        'visibility',
      ] },
      { name: 'GameState', algorithm: 'btree', columns: [
        'gameState',
      ] },
      { name: 'Id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'game_Id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, GameRow),
  __table({
    name: 'kills',
    indexes: [
      { name: 'GameId', algorithm: 'btree', columns: [
        'gameId',
      ] },
      { name: 'Id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'kills_Id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, KillsRow),
  __table({
    name: 'pickup',
    indexes: [
      { name: 'GameId_GridX_GridY', algorithm: 'btree', columns: [
        'gameId',
        'gridX',
        'gridY',
      ] },
      { name: 'GameId', algorithm: 'btree', columns: [
        'gameId',
      ] },
      { name: 'Id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'pickup_Id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PickupRow),
  __table({
    name: 'player',
    indexes: [
      { name: 'Id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'Identity', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'player_Id_key', constraint: 'unique', columns: ['id'] },
      { name: 'player_Identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, PlayerRow),
  __table({
    name: 'projectile',
    indexes: [
      { name: 'GameId', algorithm: 'btree', columns: [
        'gameId',
      ] },
      { name: 'Id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'projectile_Id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ProjectileRow),
  __table({
    name: 'projectile_transform',
    indexes: [
      { name: 'GameId', algorithm: 'btree', columns: [
        'gameId',
      ] },
      { name: 'ProjectileId', algorithm: 'btree', columns: [
        'projectileId',
      ] },
    ],
    constraints: [
      { name: 'projectile_transform_ProjectileId_key', constraint: 'unique', columns: ['projectileId'] },
    ],
  }, ProjectileTransformRow),
  __table({
    name: 'score',
    indexes: [
      { name: 'GameId', algorithm: 'btree', columns: [
        'gameId',
      ] },
    ],
    constraints: [
      { name: 'score_GameId_key', constraint: 'unique', columns: ['gameId'] },
    ],
  }, ScoreRow),
  __table({
    name: 'tank',
    indexes: [
      { name: 'GameId_IsBot', algorithm: 'btree', columns: [
        'gameId',
        'isBot',
      ] },
      { name: 'GameId_Owner', algorithm: 'btree', columns: [
        'gameId',
        'owner',
      ] },
      { name: 'GameId_TargetCode', algorithm: 'btree', columns: [
        'gameId',
        'targetCode',
      ] },
      { name: 'GameId', algorithm: 'btree', columns: [
        'gameId',
      ] },
      { name: 'Id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'Owner', algorithm: 'btree', columns: [
        'owner',
      ] },
    ],
    constraints: [
      { name: 'tank_Id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, TankRow),
  __table({
    name: 'tank_fire_state',
    indexes: [
      { name: 'GameId', algorithm: 'btree', columns: [
        'gameId',
      ] },
      { name: 'TankId', algorithm: 'btree', columns: [
        'tankId',
      ] },
    ],
    constraints: [
      { name: 'tank_fire_state_TankId_key', constraint: 'unique', columns: ['tankId'] },
    ],
  }, TankFireStateRow),
  __table({
    name: 'tank_path',
    indexes: [
      { name: 'GameId_Owner', algorithm: 'btree', columns: [
        'gameId',
        'owner',
      ] },
      { name: 'GameId', algorithm: 'btree', columns: [
        'gameId',
      ] },
      { name: 'TankId', algorithm: 'btree', columns: [
        'tankId',
      ] },
    ],
    constraints: [
      { name: 'tank_path_TankId_key', constraint: 'unique', columns: ['tankId'] },
    ],
  }, TankPathRow),
  __table({
    name: 'tank_transform',
    indexes: [
      { name: 'GameId_CollisionRegionX_CollisionRegionY', algorithm: 'btree', columns: [
        'gameId',
        'collisionRegionX',
        'collisionRegionY',
      ] },
      { name: 'GameId', algorithm: 'btree', columns: [
        'gameId',
      ] },
      { name: 'TankId', algorithm: 'btree', columns: [
        'tankId',
      ] },
    ],
    constraints: [
      { name: 'tank_transform_TankId_key', constraint: 'unique', columns: ['tankId'] },
    ],
  }, TankTransformRow),
  __table({
    name: 'terrain_detail',
    indexes: [
      { name: 'GameId_GridX_GridY', algorithm: 'btree', columns: [
        'gameId',
        'gridX',
        'gridY',
      ] },
      { name: 'GameId', algorithm: 'btree', columns: [
        'gameId',
      ] },
      { name: 'Id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'terrain_detail_Id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, TerrainDetailRow),
  __table({
    name: 'traversibility_map',
    indexes: [
      { name: 'GameId', algorithm: 'btree', columns: [
        'gameId',
      ] },
    ],
    constraints: [
      { name: 'traversibility_map_GameId_key', constraint: 'unique', columns: ['gameId'] },
    ],
  }, TraversibilityMapRow),
);

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("aim", Aim),
  __reducerSchema("changeName", ChangeName),
  __reducerSchema("CheckAndRespawnEnemyTanks", CheckAndRespawnEnemyTanks),
  __reducerSchema("CleanupResultsGames", CleanupResultsGames),
  __reducerSchema("createGame", CreateGame),
  __reducerSchema("delete_kill", DeleteKill),
  __reducerSchema("drive", Drive),
  __reducerSchema("EndGame", EndGame),
  __reducerSchema("ensureHomegame", EnsureHomegame),
  __reducerSchema("exitGame", ExitGame),
  __reducerSchema("fire", Fire),
  __reducerSchema("homeWorldProjectileExpire", HomeWorldProjectileExpire),
  __reducerSchema("homeWorldProjectileTankHit", HomeWorldProjectileTankHit),
  __reducerSchema("homeWorldProjectileTerrainHit", HomeWorldProjectileTerrainHit),
  __reducerSchema("joinGame", JoinGame),
  __reducerSchema("ping", Ping),
  __reducerSchema("ResetGame", ResetGame),
  __reducerSchema("respawn", Respawn),
  __reducerSchema("SpawnPickup", SpawnPickup),
  __reducerSchema("stop", Stop),
  __reducerSchema("switchGun", SwitchGun),
  __reducerSchema("track", Track),
  __reducerSchema("UpdateAI", UpdateAi),
  __reducerSchema("UpdateProjectiles", UpdateProjectiles),
  __reducerSchema("UpdateTanks", UpdateTanks),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "1.10.0" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. */
export const tables = __convertToAccessorMap(tablesSchema.schemaType.tables);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

