// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.10.0 (commit 1d576dc75ca066879f6d9ee4d156c5bce940bd31).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  convertToAccessorMap as __convertToAccessorMap,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import and reexport all reducer arg types
import Aim from "./aim_reducer";
export { Aim };
import CleanupResultsGames from "./cleanup_results_games_reducer";
export { CleanupResultsGames };
import CleanupSmokeCloud from "./cleanup_smoke_cloud_reducer";
export { CleanupSmokeCloud };
import DeleteKill from "./delete_kill_reducer";
export { DeleteKill };
import DriveTo from "./drive_to_reducer";
export { DriveTo };
import DriveToTank from "./drive_to_tank_reducer";
export { DriveToTank };
import EndGame from "./end_game_reducer";
export { EndGame };
import FindWorld from "./find_world_reducer";
export { FindWorld };
import Fire from "./fire_reducer";
export { Fire };
import HandleConnect from "./handle_connect_reducer";
export { HandleConnect };
import HandleDisconnect from "./handle_disconnect_reducer";
export { HandleDisconnect };
import ResetWorld from "./reset_world_reducer";
export { ResetWorld };
import Respawn from "./respawn_reducer";
export { Respawn };
import Reverse from "./reverse_reducer";
export { Reverse };
import Smokescreen from "./smokescreen_reducer";
export { Smokescreen };
import SpawnPickup from "./spawn_pickup_reducer";
export { SpawnPickup };
import Stop from "./stop_reducer";
export { Stop };
import SwitchGun from "./switch_gun_reducer";
export { SwitchGun };
import TargetTank from "./target_tank_reducer";
export { TargetTank };
import UpdateAi from "./update_ai_reducer";
export { UpdateAi };
import UpdateProjectiles from "./update_projectiles_reducer";
export { UpdateProjectiles };
import UpdateSpiderMines from "./update_spider_mines_reducer";
export { UpdateSpiderMines };
import UpdateTanks from "./update_tanks_reducer";
export { UpdateTanks };

// Import and reexport all procedure arg types

// Import and reexport all table handle types
import ScheduledAiUpdateRow from "./scheduled_ai_update_table";
export { ScheduledAiUpdateRow };
import ScheduledGameCleanupRow from "./scheduled_game_cleanup_table";
export { ScheduledGameCleanupRow };
import ScheduledGameEndRow from "./scheduled_game_end_table";
export { ScheduledGameEndRow };
import ScheduledPickupSpawnRow from "./scheduled_pickup_spawn_table";
export { ScheduledPickupSpawnRow };
import ScheduledProjectileUpdatesRow from "./scheduled_projectile_updates_table";
export { ScheduledProjectileUpdatesRow };
import ScheduledSmokeCloudCleanupRow from "./scheduled_smoke_cloud_cleanup_table";
export { ScheduledSmokeCloudCleanupRow };
import ScheduledSpiderMineUpdatesRow from "./scheduled_spider_mine_updates_table";
export { ScheduledSpiderMineUpdatesRow };
import ScheduledTankUpdatesRow from "./scheduled_tank_updates_table";
export { ScheduledTankUpdatesRow };
import ScheduledWorldResetRow from "./scheduled_world_reset_table";
export { ScheduledWorldResetRow };
import KillsRow from "./kills_table";
export { KillsRow };
import PickupRow from "./pickup_table";
export { PickupRow };
import PlayerRow from "./player_table";
export { PlayerRow };
import ProjectileRow from "./projectile_table";
export { ProjectileRow };
import ProjectileTrailRow from "./projectile_trail_table";
export { ProjectileTrailRow };
import ScoreRow from "./score_table";
export { ScoreRow };
import SmokeCloudRow from "./smoke_cloud_table";
export { SmokeCloudRow };
import SpiderMineRow from "./spider_mine_table";
export { SpiderMineRow };
import TankRow from "./tank_table";
export { TankRow };
import TerrainDetailRow from "./terrain_detail_table";
export { TerrainDetailRow };
import TraversibilityMapRow from "./traversibility_map_table";
export { TraversibilityMapRow };
import WorldRow from "./world_table";
export { WorldRow };

// Import and reexport all types
import BaseTerrain from "./base_terrain_type";
export { BaseTerrain };
import ExplosionTrigger from "./explosion_trigger_type";
export { ExplosionTrigger };
import GameState from "./game_state_type";
export { GameState };
import Gun from "./gun_type";
export { Gun };
import GunType from "./gun_type_type";
export { GunType };
import Kill from "./kill_type";
export { Kill };
import PathEntry from "./path_entry_type";
export { PathEntry };
import Pickup from "./pickup_type";
export { Pickup };
import PickupType from "./pickup_type_type";
export { PickupType };
import Player from "./player_type";
export { Player };
import Projectile from "./projectile_type";
export { Projectile };
import ProjectileType from "./projectile_type_type";
export { ProjectileType };
import ProjectileTrail from "./projectile_trail_type";
export { ProjectileTrail };
import ProjectileTrailType from "./projectile_trail_type_type";
export { ProjectileTrailType };
import ScheduledAiUpdate from "./scheduled_ai_update_type";
export { ScheduledAiUpdate };
import ScheduledGameCleanup from "./scheduled_game_cleanup_type";
export { ScheduledGameCleanup };
import ScheduledGameEnd from "./scheduled_game_end_type";
export { ScheduledGameEnd };
import ScheduledPickupSpawn from "./scheduled_pickup_spawn_type";
export { ScheduledPickupSpawn };
import ScheduledProjectileUpdates from "./scheduled_projectile_updates_type";
export { ScheduledProjectileUpdates };
import ScheduledSmokeCloudCleanup from "./scheduled_smoke_cloud_cleanup_type";
export { ScheduledSmokeCloudCleanup };
import ScheduledSpiderMineUpdates from "./scheduled_spider_mine_updates_type";
export { ScheduledSpiderMineUpdates };
import ScheduledTankUpdates from "./scheduled_tank_updates_type";
export { ScheduledTankUpdates };
import ScheduledWorldReset from "./scheduled_world_reset_type";
export { ScheduledWorldReset };
import Score from "./score_type";
export { Score };
import SmokeCloud from "./smoke_cloud_type";
export { SmokeCloud };
import SpiderMine from "./spider_mine_type";
export { SpiderMine };
import Tank from "./tank_type";
export { Tank };
import TerrainDetail from "./terrain_detail_type";
export { TerrainDetail };
import TerrainDetailType from "./terrain_detail_type_type";
export { TerrainDetailType };
import TraversibilityMap from "./traversibility_map_type";
export { TraversibilityMap };
import Vector2Float from "./vector_2_float_type";
export { Vector2Float };
import World from "./world_type";
export { World };

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema(
  __table({
    name: 'ScheduledAIUpdate',
    indexes: [
      { name: 'ScheduledId', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
      { name: 'WorldId', algorithm: 'btree', columns: [
        'worldId',
      ] },
    ],
    constraints: [
      { name: 'ScheduledAIUpdate_ScheduledId_key', constraint: 'unique', columns: ['scheduledId'] },
    ],
  }, ScheduledAiUpdateRow),
  __table({
    name: 'ScheduledGameCleanup',
    indexes: [
      { name: 'ScheduledId', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
    ],
    constraints: [
      { name: 'ScheduledGameCleanup_ScheduledId_key', constraint: 'unique', columns: ['scheduledId'] },
    ],
  }, ScheduledGameCleanupRow),
  __table({
    name: 'ScheduledGameEnd',
    indexes: [
      { name: 'ScheduledId', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
      { name: 'WorldId', algorithm: 'btree', columns: [
        'worldId',
      ] },
    ],
    constraints: [
      { name: 'ScheduledGameEnd_ScheduledId_key', constraint: 'unique', columns: ['scheduledId'] },
    ],
  }, ScheduledGameEndRow),
  __table({
    name: 'ScheduledPickupSpawn',
    indexes: [
      { name: 'ScheduledId', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
      { name: 'WorldId', algorithm: 'btree', columns: [
        'worldId',
      ] },
    ],
    constraints: [
      { name: 'ScheduledPickupSpawn_ScheduledId_key', constraint: 'unique', columns: ['scheduledId'] },
    ],
  }, ScheduledPickupSpawnRow),
  __table({
    name: 'ScheduledProjectileUpdates',
    indexes: [
      { name: 'ScheduledId', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
      { name: 'WorldId', algorithm: 'btree', columns: [
        'worldId',
      ] },
    ],
    constraints: [
      { name: 'ScheduledProjectileUpdates_ScheduledId_key', constraint: 'unique', columns: ['scheduledId'] },
    ],
  }, ScheduledProjectileUpdatesRow),
  __table({
    name: 'ScheduledSmokeCloudCleanup',
    indexes: [
      { name: 'ScheduledId', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
      { name: 'SmokeCloudId', algorithm: 'btree', columns: [
        'smokeCloudId',
      ] },
    ],
    constraints: [
      { name: 'ScheduledSmokeCloudCleanup_ScheduledId_key', constraint: 'unique', columns: ['scheduledId'] },
    ],
  }, ScheduledSmokeCloudCleanupRow),
  __table({
    name: 'ScheduledSpiderMineUpdates',
    indexes: [
      { name: 'ScheduledId', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
      { name: 'WorldId', algorithm: 'btree', columns: [
        'worldId',
      ] },
    ],
    constraints: [
      { name: 'ScheduledSpiderMineUpdates_ScheduledId_key', constraint: 'unique', columns: ['scheduledId'] },
    ],
  }, ScheduledSpiderMineUpdatesRow),
  __table({
    name: 'ScheduledTankUpdates',
    indexes: [
      { name: 'ScheduledId', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
      { name: 'WorldId', algorithm: 'btree', columns: [
        'worldId',
      ] },
    ],
    constraints: [
      { name: 'ScheduledTankUpdates_ScheduledId_key', constraint: 'unique', columns: ['scheduledId'] },
    ],
  }, ScheduledTankUpdatesRow),
  __table({
    name: 'ScheduledWorldReset',
    indexes: [
      { name: 'ScheduledId', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
    ],
    constraints: [
      { name: 'ScheduledWorldReset_ScheduledId_key', constraint: 'unique', columns: ['scheduledId'] },
    ],
  }, ScheduledWorldResetRow),
  __table({
    name: 'kills',
    indexes: [
      { name: 'Id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'WorldId', algorithm: 'btree', columns: [
        'worldId',
      ] },
    ],
    constraints: [
      { name: 'kills_Id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, KillsRow),
  __table({
    name: 'pickup',
    indexes: [
      { name: 'Id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'WorldId_GridX_GridY', algorithm: 'btree', columns: [
        'worldId',
        'gridX',
        'gridY',
      ] },
      { name: 'WorldId', algorithm: 'btree', columns: [
        'worldId',
      ] },
    ],
    constraints: [
      { name: 'pickup_Id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PickupRow),
  __table({
    name: 'player',
    indexes: [
      { name: 'Id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'Identity', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'player_Id_key', constraint: 'unique', columns: ['id'] },
      { name: 'player_Identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, PlayerRow),
  __table({
    name: 'projectile',
    indexes: [
      { name: 'Id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'WorldId', algorithm: 'btree', columns: [
        'worldId',
      ] },
    ],
    constraints: [
      { name: 'projectile_Id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ProjectileRow),
  __table({
    name: 'projectile_trail',
    indexes: [
      { name: 'Id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'WorldId', algorithm: 'btree', columns: [
        'worldId',
      ] },
    ],
    constraints: [
      { name: 'projectile_trail_Id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ProjectileTrailRow),
  __table({
    name: 'score',
    indexes: [
      { name: 'WorldId', algorithm: 'btree', columns: [
        'worldId',
      ] },
    ],
    constraints: [
      { name: 'score_WorldId_key', constraint: 'unique', columns: ['worldId'] },
    ],
  }, ScoreRow),
  __table({
    name: 'smoke_cloud',
    indexes: [
      { name: 'Id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'WorldId_CollisionRegionX_CollisionRegionY', algorithm: 'btree', columns: [
        'worldId',
        'collisionRegionX',
        'collisionRegionY',
      ] },
      { name: 'WorldId', algorithm: 'btree', columns: [
        'worldId',
      ] },
    ],
    constraints: [
      { name: 'smoke_cloud_Id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, SmokeCloudRow),
  __table({
    name: 'spider_mine',
    indexes: [
      { name: 'Id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'WorldId_CollisionRegionX_CollisionRegionY', algorithm: 'btree', columns: [
        'worldId',
        'collisionRegionX',
        'collisionRegionY',
      ] },
      { name: 'WorldId', algorithm: 'btree', columns: [
        'worldId',
      ] },
    ],
    constraints: [
      { name: 'spider_mine_Id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, SpiderMineRow),
  __table({
    name: 'tank',
    indexes: [
      { name: 'Id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'Owner', algorithm: 'btree', columns: [
        'owner',
      ] },
      { name: 'WorldId_CollisionRegionX_CollisionRegionY', algorithm: 'btree', columns: [
        'worldId',
        'collisionRegionX',
        'collisionRegionY',
      ] },
      { name: 'WorldId_IsBot', algorithm: 'btree', columns: [
        'worldId',
        'isBot',
      ] },
      { name: 'WorldId_Name', algorithm: 'btree', columns: [
        'worldId',
        'name',
      ] },
      { name: 'WorldId_Owner', algorithm: 'btree', columns: [
        'worldId',
        'owner',
      ] },
      { name: 'WorldId', algorithm: 'btree', columns: [
        'worldId',
      ] },
    ],
    constraints: [
      { name: 'tank_Id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, TankRow),
  __table({
    name: 'terrain_detail',
    indexes: [
      { name: 'Id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'WorldId_GridX_GridY', algorithm: 'btree', columns: [
        'worldId',
        'gridX',
        'gridY',
      ] },
      { name: 'WorldId', algorithm: 'btree', columns: [
        'worldId',
      ] },
    ],
    constraints: [
      { name: 'terrain_detail_Id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, TerrainDetailRow),
  __table({
    name: 'traversibility_map',
    indexes: [
      { name: 'WorldId', algorithm: 'btree', columns: [
        'worldId',
      ] },
    ],
    constraints: [
      { name: 'traversibility_map_WorldId_key', constraint: 'unique', columns: ['worldId'] },
    ],
  }, TraversibilityMapRow),
  __table({
    name: 'world',
    indexes: [
      { name: 'GameState', algorithm: 'btree', columns: [
        'gameState',
      ] },
      { name: 'Id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'world_Id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, WorldRow),
);

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("aim", Aim),
  __reducerSchema("CleanupResultsGames", CleanupResultsGames),
  __reducerSchema("CleanupSmokeCloud", CleanupSmokeCloud),
  __reducerSchema("delete_kill", DeleteKill),
  __reducerSchema("driveTo", DriveTo),
  __reducerSchema("driveToTank", DriveToTank),
  __reducerSchema("EndGame", EndGame),
  __reducerSchema("findWorld", FindWorld),
  __reducerSchema("fire", Fire),
  __reducerSchema("ResetWorld", ResetWorld),
  __reducerSchema("respawn", Respawn),
  __reducerSchema("reverse", Reverse),
  __reducerSchema("smokescreen", Smokescreen),
  __reducerSchema("SpawnPickup", SpawnPickup),
  __reducerSchema("stop", Stop),
  __reducerSchema("switchGun", SwitchGun),
  __reducerSchema("targetTank", TargetTank),
  __reducerSchema("UpdateAI", UpdateAi),
  __reducerSchema("UpdateProjectiles", UpdateProjectiles),
  __reducerSchema("UpdateSpiderMines", UpdateSpiderMines),
  __reducerSchema("UpdateTanks", UpdateTanks),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "1.10.0" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. */
export const tables = __convertToAccessorMap(tablesSchema.schemaType.tables);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

