// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.11.1 (commit bbfa851b45db7096aa2a69d7dbad84f52983559f).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  convertToAccessorMap as __convertToAccessorMap,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import and reexport all reducer arg types
import AimReducer from "./aim_reducer";
export { AimReducer };
import DriveReducer from "./drive_reducer";
export { DriveReducer };
import DriveToReducer from "./drive_to_reducer";
export { DriveToReducer };
import FindWorldReducer from "./find_world_reducer";
export { FindWorldReducer };
import FireReducer from "./fire_reducer";
export { FireReducer };
import HandleConnectReducer from "./handle_connect_reducer";
export { HandleConnectReducer };
import HandleDisconnectReducer from "./handle_disconnect_reducer";
export { HandleDisconnectReducer };
import NavigateToTankReducer from "./navigate_to_tank_reducer";
export { NavigateToTankReducer };
import ResetWorldReducer from "./reset_world_reducer";
export { ResetWorldReducer };
import RespawnReducer from "./respawn_reducer";
export { RespawnReducer };
import ReverseReducer from "./reverse_reducer";
export { ReverseReducer };
import SpawnPickupReducer from "./spawn_pickup_reducer";
export { SpawnPickupReducer };
import StopReducer from "./stop_reducer";
export { StopReducer };
import SwitchGunReducer from "./switch_gun_reducer";
export { SwitchGunReducer };
import TargetTankReducer from "./target_tank_reducer";
export { TargetTankReducer };
import UpdateAiReducer from "./update_ai_reducer";
export { UpdateAiReducer };
import UpdateProjectilesReducer from "./update_projectiles_reducer";
export { UpdateProjectilesReducer };
import UpdateTanksReducer from "./update_tanks_reducer";
export { UpdateTanksReducer };

// Import and reexport all procedure arg types

// Import and reexport all table handle types
import ScheduledAiUpdateRow from "./scheduled_ai_update_table";
export { ScheduledAiUpdateRow };
import ScheduledPickupSpawnRow from "./scheduled_pickup_spawn_table";
export { ScheduledPickupSpawnRow };
import ScheduledProjectileUpdatesRow from "./scheduled_projectile_updates_table";
export { ScheduledProjectileUpdatesRow };
import ScheduledTankUpdatesRow from "./scheduled_tank_updates_table";
export { ScheduledTankUpdatesRow };
import ScheduledWorldResetRow from "./scheduled_world_reset_table";
export { ScheduledWorldResetRow };
import PickupRow from "./pickup_table";
export { PickupRow };
import PlayerRow from "./player_table";
export { PlayerRow };
import ProjectileRow from "./projectile_table";
export { ProjectileRow };
import ScoreRow from "./score_table";
export { ScoreRow };
import TankRow from "./tank_table";
export { TankRow };
import TerrainDetailRow from "./terrain_detail_table";
export { TerrainDetailRow };
import TraversibilityMapRow from "./traversibility_map_table";
export { TraversibilityMapRow };
import WorldRow from "./world_table";
export { WorldRow };

// Import and reexport all types
import BaseTerrain from "./base_terrain_type";
export { BaseTerrain };
import ExplosionTrigger from "./explosion_trigger_type";
export { ExplosionTrigger };
import GameState from "./game_state_type";
export { GameState };
import Gun from "./gun_type";
export { Gun };
import GunType from "./gun_type_type";
export { GunType };
import PathEntry from "./path_entry_type";
export { PathEntry };
import Pickup from "./pickup_type";
export { Pickup };
import Player from "./player_type";
export { Player };
import Projectile from "./projectile_type";
export { Projectile };
import ProjectileType from "./projectile_type_type";
export { ProjectileType };
import ScheduledAiUpdate from "./scheduled_ai_update_type";
export { ScheduledAiUpdate };
import ScheduledPickupSpawn from "./scheduled_pickup_spawn_type";
export { ScheduledPickupSpawn };
import ScheduledProjectileUpdates from "./scheduled_projectile_updates_type";
export { ScheduledProjectileUpdates };
import ScheduledTankUpdates from "./scheduled_tank_updates_type";
export { ScheduledTankUpdates };
import ScheduledWorldReset from "./scheduled_world_reset_type";
export { ScheduledWorldReset };
import Score from "./score_type";
export { Score };
import Tank from "./tank_type";
export { Tank };
import TerrainDetail from "./terrain_detail_type";
export { TerrainDetail };
import TerrainDetailType from "./terrain_detail_type_type";
export { TerrainDetailType };
import TraversibilityMap from "./traversibility_map_type";
export { TraversibilityMap };
import Vector2 from "./vector_2_type";
export { Vector2 };
import Vector2Float from "./vector_2_float_type";
export { Vector2Float };
import World from "./world_type";
export { World };

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema(
  __table({
    name: 'ScheduledAIUpdate',
    indexes: [
      { name: 'ScheduledId', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
    ],
    constraints: [
      { name: 'ScheduledAIUpdate_ScheduledId_key', constraint: 'unique', columns: ['scheduledId'] },
    ],
  }, ScheduledAiUpdateRow),
  __table({
    name: 'ScheduledPickupSpawn',
    indexes: [
      { name: 'ScheduledId', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
      { name: 'WorldId', algorithm: 'btree', columns: [
        'worldId',
      ] },
    ],
    constraints: [
      { name: 'ScheduledPickupSpawn_ScheduledId_key', constraint: 'unique', columns: ['scheduledId'] },
    ],
  }, ScheduledPickupSpawnRow),
  __table({
    name: 'ScheduledProjectileUpdates',
    indexes: [
      { name: 'ScheduledId', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
      { name: 'WorldId', algorithm: 'btree', columns: [
        'worldId',
      ] },
    ],
    constraints: [
      { name: 'ScheduledProjectileUpdates_ScheduledId_key', constraint: 'unique', columns: ['scheduledId'] },
    ],
  }, ScheduledProjectileUpdatesRow),
  __table({
    name: 'ScheduledTankUpdates',
    indexes: [
      { name: 'ScheduledId', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
      { name: 'WorldId', algorithm: 'btree', columns: [
        'worldId',
      ] },
    ],
    constraints: [
      { name: 'ScheduledTankUpdates_ScheduledId_key', constraint: 'unique', columns: ['scheduledId'] },
    ],
  }, ScheduledTankUpdatesRow),
  __table({
    name: 'ScheduledWorldReset',
    indexes: [
      { name: 'ScheduledId', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
    ],
    constraints: [
      { name: 'ScheduledWorldReset_ScheduledId_key', constraint: 'unique', columns: ['scheduledId'] },
    ],
  }, ScheduledWorldResetRow),
  __table({
    name: 'pickup',
    indexes: [
      { name: 'Id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'WorldId_PositionX_PositionY', algorithm: 'btree', columns: [
        'worldId',
        'positionX',
        'positionY',
      ] },
      { name: 'WorldId', algorithm: 'btree', columns: [
        'worldId',
      ] },
    ],
    constraints: [
      { name: 'pickup_Id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PickupRow),
  __table({
    name: 'player',
    indexes: [
      { name: 'Id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'Identity', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'player_Id_key', constraint: 'unique', columns: ['id'] },
      { name: 'player_Identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, PlayerRow),
  __table({
    name: 'projectile',
    indexes: [
      { name: 'Id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'WorldId', algorithm: 'btree', columns: [
        'worldId',
      ] },
    ],
    constraints: [
      { name: 'projectile_Id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ProjectileRow),
  __table({
    name: 'score',
    indexes: [
      { name: 'WorldId', algorithm: 'btree', columns: [
        'worldId',
      ] },
    ],
    constraints: [
      { name: 'score_WorldId_key', constraint: 'unique', columns: ['worldId'] },
    ],
  }, ScoreRow),
  __table({
    name: 'tank',
    indexes: [
      { name: 'Id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'Owner', algorithm: 'btree', columns: [
        'owner',
      ] },
      { name: 'WorldId_CollisionRegionX_CollisionRegionY', algorithm: 'btree', columns: [
        'worldId',
        'collisionRegionX',
        'collisionRegionY',
      ] },
      { name: 'WorldId_IsBot', algorithm: 'btree', columns: [
        'worldId',
        'isBot',
      ] },
      { name: 'WorldId_Name', algorithm: 'btree', columns: [
        'worldId',
        'name',
      ] },
      { name: 'WorldId_Owner', algorithm: 'btree', columns: [
        'worldId',
        'owner',
      ] },
      { name: 'WorldId', algorithm: 'btree', columns: [
        'worldId',
      ] },
    ],
    constraints: [
      { name: 'tank_Id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, TankRow),
  __table({
    name: 'terrain_detail',
    indexes: [
      { name: 'Id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'WorldId_PositionX_PositionY', algorithm: 'btree', columns: [
        'worldId',
        'positionX',
        'positionY',
      ] },
      { name: 'WorldId', algorithm: 'btree', columns: [
        'worldId',
      ] },
    ],
    constraints: [
      { name: 'terrain_detail_Id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, TerrainDetailRow),
  __table({
    name: 'traversibility_map',
    indexes: [
      { name: 'WorldId', algorithm: 'btree', columns: [
        'worldId',
      ] },
    ],
    constraints: [
      { name: 'traversibility_map_WorldId_key', constraint: 'unique', columns: ['worldId'] },
    ],
  }, TraversibilityMapRow),
  __table({
    name: 'world',
    indexes: [
      { name: 'Id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'world_Id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, WorldRow),
);

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("aim", AimReducer),
  __reducerSchema("drive", DriveReducer),
  __reducerSchema("driveTo", DriveToReducer),
  __reducerSchema("findWorld", FindWorldReducer),
  __reducerSchema("fire", FireReducer),
  __reducerSchema("navigateToTank", NavigateToTankReducer),
  __reducerSchema("ResetWorld", ResetWorldReducer),
  __reducerSchema("respawn", RespawnReducer),
  __reducerSchema("reverse", ReverseReducer),
  __reducerSchema("SpawnPickup", SpawnPickupReducer),
  __reducerSchema("stop", StopReducer),
  __reducerSchema("switchGun", SwitchGunReducer),
  __reducerSchema("targetTank", TargetTankReducer),
  __reducerSchema("UpdateAI", UpdateAiReducer),
  __reducerSchema("UpdateProjectiles", UpdateProjectilesReducer),
  __reducerSchema("UpdateTanks", UpdateTanksReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "1.11.1" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. */
export const tables = __convertToAccessorMap(tablesSchema.schemaType.tables);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

