// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  worldId: __t.string(),
  killer: __t.string(),
  killee: __t.string(),
  killeeName: __t.string(),
  killerAlliance: __t.i32(),
  killeeAlliance: __t.i32(),
  timestamp: __t.u64(),
  acked: __t.bool(),
});
