// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import PickupType from "./pickup_type_type";


export default __t.row({
  id: __t.string().primaryKey().name("Id"),
  worldId: __t.string().name("WorldId"),
  positionX: __t.f32().name("PositionX"),
  positionY: __t.f32().name("PositionY"),
  gridX: __t.i32().name("GridX"),
  gridY: __t.i32().name("GridY"),
  get type() {
    return PickupType.name("Type");
  },
});
