// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

// The tagged union or sum type for the algebraic type `PickupType`.
const PickupType = __t.enum("PickupType", {TripleShooter: __t.unit(),
  MissileLauncher: __t.unit(),
  Health: __t.unit(),
  Boomerang: __t.unit(),
  Grenade: __t.unit(),
  Rocket: __t.unit(),
  Moag: __t.unit(),
  SpiderMine: __t.unit(),
  Shield: __t.unit(),
  Sniper: __t.unit(),
});

export default PickupType;


