// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import Vector2Float from "./vector_2_float_type";
import ProjectileType from "./projectile_type_type";
import ExplosionTrigger from "./explosion_trigger_type";


export default __t.row({
  id: __t.string().primaryKey().name("Id"),
  worldId: __t.string().name("WorldId"),
  shooterTankId: __t.string().name("ShooterTankId"),
  alliance: __t.i32().name("Alliance"),
  positionX: __t.f32().name("PositionX"),
  positionY: __t.f32().name("PositionY"),
  speed: __t.f32().name("Speed"),
  size: __t.f32().name("Size"),
  get velocity() {
    return Vector2Float.name("Velocity");
  },
  damage: __t.i32().name("Damage"),
  trackingStrength: __t.f32().name("TrackingStrength"),
  get projectileType() {
    return ProjectileType.name("ProjectileType");
  },
  spawnedAt: __t.u64().name("SpawnedAt"),
  lifetimeSeconds: __t.f32().name("LifetimeSeconds"),
  returnsToShooter: __t.bool().name("ReturnsToShooter"),
  isReturning: __t.bool().name("IsReturning"),
  maxCollisions: __t.i32().name("MaxCollisions"),
  collisionCount: __t.i32().name("CollisionCount"),
  passThroughTerrain: __t.bool().name("PassThroughTerrain"),
  explosionRadius: __t.option(__t.f32()).name("ExplosionRadius"),
  get explosionTrigger() {
    return ExplosionTrigger.name("ExplosionTrigger");
  },
  bounceDamping: __t.option(__t.f32()).name("BounceDamping"),
});
