// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import ProjectileType from "./projectile_type_type";
import ExplosionTrigger from "./explosion_trigger_type";
import DamagedTile from "./damaged_tile_type";
import DamagedTank from "./damaged_tank_type";


export default __t.object("Projectile", {
  id: __t.u64(),
  gameId: __t.string(),
  shooterTankId: __t.string(),
  alliance: __t.i32(),
  size: __t.f32(),
  damage: __t.i32(),
  trackingStrength: __t.f32(),
  trackingRadius: __t.f32(),
  get projectileType() {
    return ProjectileType;
  },
  spawnedAt: __t.u64(),
  lifetimeSeconds: __t.f32(),
  returnsToShooter: __t.bool(),
  maxCollisions: __t.i32(),
  passThroughTerrain: __t.bool(),
  collisionRadius: __t.f32(),
  explosionRadius: __t.option(__t.f32()),
  get explosionTrigger() {
    return ExplosionTrigger;
  },
  damping: __t.option(__t.f32()),
  bounce: __t.bool(),
  speed: __t.f32(),
  isReturning: __t.bool(),
  get recentlyDamagedTiles() {
    return __t.array(DamagedTile);
  },
  get recentlyHitTanks() {
    return __t.array(DamagedTank);
  },
});


