// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import ProjectileTrailType from "./projectile_trail_type_type";


export default __t.row({
  id: __t.string().primaryKey().name("Id"),
  worldId: __t.string().name("WorldId"),
  startX: __t.f32().name("StartX"),
  startY: __t.f32().name("StartY"),
  endX: __t.f32().name("EndX"),
  endY: __t.f32().name("EndY"),
  get type() {
    return ProjectileTrailType.name("Type");
  },
  spawnedAt: __t.u64().name("SpawnedAt"),
});
