// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import ProjectileType from "./projectile_type_type";
import ExplosionTrigger from "./explosion_trigger_type";
import DamagedTile from "./damaged_tile_type";
import DamagedTank from "./damaged_tank_type";


export default __t.row({
  id: __t.u64().primaryKey().name("Id"),
  gameId: __t.string().name("GameId"),
  shooterTankId: __t.string().name("ShooterTankId"),
  alliance: __t.i32().name("Alliance"),
  size: __t.f32().name("Size"),
  damage: __t.i32().name("Damage"),
  trackingStrength: __t.f32().name("TrackingStrength"),
  trackingRadius: __t.f32().name("TrackingRadius"),
  get projectileType() {
    return ProjectileType.name("ProjectileType");
  },
  spawnedAt: __t.u64().name("SpawnedAt"),
  lifetimeSeconds: __t.f32().name("LifetimeSeconds"),
  returnsToShooter: __t.bool().name("ReturnsToShooter"),
  maxCollisions: __t.i32().name("MaxCollisions"),
  passThroughTerrain: __t.bool().name("PassThroughTerrain"),
  collisionRadius: __t.f32().name("CollisionRadius"),
  explosionRadius: __t.option(__t.f32()).name("ExplosionRadius"),
  get explosionTrigger() {
    return ExplosionTrigger.name("ExplosionTrigger");
  },
  damping: __t.option(__t.f32()).name("Damping"),
  bounce: __t.bool().name("Bounce"),
  speed: __t.f32().name("Speed"),
  isReturning: __t.bool().name("IsReturning"),
  get recentlyDamagedTiles() {
    return __t.array(DamagedTile).name("RecentlyDamagedTiles");
  },
  get recentlyHitTanks() {
    return __t.array(DamagedTank).name("RecentlyHitTanks");
  },
});
