// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import Vector2Float from "./vector_2_float_type";


export default __t.object("Projectile", {
  id: __t.string(),
  worldId: __t.string(),
  shooterTankId: __t.string(),
  alliance: __t.i32(),
  positionX: __t.f32(),
  positionY: __t.f32(),
  speed: __t.f32(),
  size: __t.f32(),
  get velocity() {
    return Vector2Float;
  },
});


