// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  Vector2Float,
} from "./types";


export default __t.row({
  projectileId: __t.u64().primaryKey().name("projectile_id"),
  gameId: __t.string().name("game_id"),
  positionX: __t.f32().name("position_x"),
  positionY: __t.f32().name("position_y"),
  get velocity() {
    return Vector2Float;
  },
  collisionCount: __t.i32().name("collision_count"),
});
