// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import Vector2Float from "./vector_2_float_type";
import ProjectileType from "./projectile_type_type";
import ExplosionTrigger from "./explosion_trigger_type";


export default __t.object("Projectile", {
  id: __t.string(),
  worldId: __t.string(),
  shooterTankId: __t.string(),
  alliance: __t.i32(),
  positionX: __t.f32(),
  positionY: __t.f32(),
  speed: __t.f32(),
  size: __t.f32(),
  get velocity() {
    return Vector2Float;
  },
  damage: __t.i32(),
  trackingStrength: __t.f32(),
  get projectileType() {
    return ProjectileType;
  },
  spawnedAt: __t.u64(),
  lifetimeSeconds: __t.f32(),
  returnsToShooter: __t.bool(),
  isReturning: __t.bool(),
  maxCollisions: __t.i32(),
  collisionCount: __t.i32(),
  passThroughTerrain: __t.bool(),
  collisionRadius: __t.f32(),
  explosionRadius: __t.option(__t.f32()),
  get explosionTrigger() {
    return ExplosionTrigger;
  },
  bounceDamping: __t.option(__t.f32()),
});


