// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import Vector2Float from "./vector_2_float_type";


export default __t.row({
  projectileId: __t.u64().primaryKey().name("ProjectileId"),
  gameId: __t.string().name("GameId"),
  positionX: __t.f32().name("PositionX"),
  positionY: __t.f32().name("PositionY"),
  get velocity() {
    return Vector2Float.name("Velocity");
  },
  collisionCount: __t.i32().name("CollisionCount"),
});
