// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.object("RaycastHit", {
  id: __t.string(),
  worldId: __t.string(),
  startX: __t.f32(),
  startY: __t.f32(),
  endX: __t.f32(),
  endY: __t.f32(),
  spawnedAt: __t.u64(),
});


