// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";


export default __t.row({
  id: __t.string().primaryKey(),
  worldId: __t.string(),
  positionX: __t.f32(),
  positionY: __t.f32(),
  spawnedAt: __t.u64(),
  radius: __t.f32(),
});
