// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import Vector2Float from "./vector_2_float_type";


export default __t.row({
  id: __t.string().primaryKey(),
  worldId: __t.string(),
  shooterTankId: __t.string(),
  alliance: __t.i32(),
  positionX: __t.f32(),
  positionY: __t.f32(),
  collisionRegionX: __t.i32(),
  collisionRegionY: __t.i32(),
  health: __t.i32(),
  targetTankId: __t.option(__t.string()),
  isPlanted: __t.bool(),
  plantingStartedAt: __t.u64(),
  get velocity() {
    return Vector2Float;
  },
});
