// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import Vector2Float from "./vector_2_float_type";


export default __t.row({
  id: __t.string().primaryKey().name("Id"),
  worldId: __t.string().name("WorldId"),
  shooterTankId: __t.string().name("ShooterTankId"),
  alliance: __t.i32().name("Alliance"),
  positionX: __t.f32().name("PositionX"),
  positionY: __t.f32().name("PositionY"),
  collisionRegionX: __t.i32().name("CollisionRegionX"),
  collisionRegionY: __t.i32().name("CollisionRegionY"),
  health: __t.i32().name("Health"),
  targetTankId: __t.option(__t.string()).name("TargetTankId"),
  isPlanted: __t.bool().name("IsPlanted"),
  plantingStartedAt: __t.u64().name("PlantingStartedAt"),
  get velocity() {
    return Vector2Float.name("Velocity");
  },
});
