// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  Vector2Float,
} from "./types";


export default __t.row({
  tankId: __t.string().primaryKey().name("tank_id"),
  gameId: __t.string().name("game_id"),
  owner: __t.identity(),
  get path() {
    return __t.array(Vector2Float);
  },
  pathIndex: __t.i32().name("path_index"),
});
