// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import Gun from "./gun_type";


export default __t.object("Tank", {
  id: __t.string(),
  worldId: __t.string(),
  health: __t.i32(),
  kills: __t.i32(),
  deaths: __t.i32(),
  killStreak: __t.i32(),
  target: __t.option(__t.string()),
  targetLead: __t.f32(),
  message: __t.option(__t.string()),
  turretAngularVelocity: __t.f32(),
  turretRotation: __t.f32(),
  targetTurretRotation: __t.f32(),
  get guns() {
    return __t.array(Gun);
  },
  selectedGunIndex: __t.i32(),
  hasShield: __t.bool(),
  remainingImmunityMicros: __t.i64(),
  deathTimestamp: __t.u64(),
  lastDamagedBy: __t.option(__t.identity()),
});


