// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.object("Tank", {
  id: __t.string(),
  worldId: __t.string(),
  player: __t.identity(),
  positionX: __t.f32(),
  positionY: __t.f32(),
  bodyRotation: __t.f32(),
  turretRotation: __t.f32(),
});


