// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import AiBehavior from "./ai_behavior_type";
import AiConfig from "./ai_config_type";


export default __t.object("TankMetadata", {
  tankId: __t.string(),
  worldId: __t.string(),
  owner: __t.identity(),
  name: __t.string(),
  targetCode: __t.string(),
  joinCode: __t.option(__t.string()),
  isBot: __t.bool(),
  get aiBehavior() {
    return AiBehavior;
  },
  get aiConfig() {
    return __t.option(AiConfig);
  },
  alliance: __t.i32(),
  maxHealth: __t.i32(),
  topSpeed: __t.f32(),
  turretRotationSpeed: __t.f32(),
});


