// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import Vector2Float from "./vector_2_float_type";


export default __t.object("TankPosition", {
  tankId: __t.string(),
  worldId: __t.string(),
  positionX: __t.f32(),
  positionY: __t.f32(),
  get velocity() {
    return Vector2Float;
  },
  collisionRegionX: __t.i32(),
  collisionRegionY: __t.i32(),
  updatedAt: __t.u64(),
});


