// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import Vector2Float from "./vector_2_float_type";
import PathEntry from "./path_entry_type";
import Gun from "./gun_type";


export default __t.object("Tank", {
  id: __t.string(),
  worldId: __t.string(),
  owner: __t.identity(),
  name: __t.string(),
  joinCode: __t.option(__t.string()),
  isBot: __t.bool(),
  alliance: __t.i32(),
  health: __t.i32(),
  maxHealth: __t.i32(),
  kills: __t.i32(),
  deaths: __t.i32(),
  collisionRegionX: __t.i32(),
  collisionRegionY: __t.i32(),
  target: __t.option(__t.string()),
  targetLead: __t.f32(),
  get path() {
    return __t.array(PathEntry);
  },
  topSpeed: __t.f32(),
  turretRotationSpeed: __t.f32(),
  positionX: __t.f32(),
  positionY: __t.f32(),
  get velocity() {
    return Vector2Float;
  },
  turretAngularVelocity: __t.f32(),
  turretRotation: __t.f32(),
  targetTurretRotation: __t.f32(),
  get guns() {
    return __t.array(Gun);
  },
  selectedGunIndex: __t.i32(),
  lastFireTime: __t.u64(),
  smokescreenCooldownEnd: __t.u64(),
  hasShield: __t.bool(),
  overdriveCooldownEnd: __t.u64(),
  overdriveActiveUntil: __t.u64(),
});


