// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  Gun,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  tankId: __t.string().name("tank_id"),
  gameId: __t.string().name("game_id"),
  slotIndex: __t.i32().name("slot_index"),
  get gun() {
    return Gun;
  },
});
