// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import PathEntry from "./path_entry_type";


export default __t.row({
  id: __t.string().primaryKey(),
  worldId: __t.string(),
  owner: __t.identity(),
  get path() {
    return __t.array(PathEntry);
  },
  topSpeed: __t.f32(),
  bodyRotationSpeed: __t.f32(),
  turretRotationSpeed: __t.f32(),
  positionX: __t.f32(),
  positionY: __t.f32(),
  velocityX: __t.f32(),
  velocityY: __t.f32(),
  bodyRotation: __t.f32(),
  turretRotation: __t.f32(),
});
