// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import PathEntry from "./path_entry_type";


export default __t.object("TankPath", {
  tankId: __t.string(),
  worldId: __t.string(),
  owner: __t.identity(),
  get path() {
    return __t.array(PathEntry);
  },
});


