// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

// The tagged union or sum type for the algebraic type `TerrainDetailType`.
const TerrainDetailType = __t.enum("TerrainDetailType", {None: __t.unit(),
  Cliff: __t.unit(),
  Rock: __t.unit(),
  Tree: __t.unit(),
  Bridge: __t.unit(),
  HayBale: __t.unit(),
  Label: __t.unit(),
  TripleShooterPickup: __t.unit(),
  MissileLauncherPickup: __t.unit(),
  HealthPickup: __t.unit(),
  BoomerangPickup: __t.unit(),
  GrenadePickup: __t.unit(),
  RocketPickup: __t.unit(),
  FoundationEdge: __t.unit(),
  FoundationCorner: __t.unit(),
  FenceEdge: __t.unit(),
  FenceCorner: __t.unit(),
  DeadTank: __t.unit(),
  TargetDummy: __t.unit(),
});

export default TerrainDetailType;


