// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import TerrainDetailType from "./terrain_detail_type_type";
import Vector2Float from "./vector_2_float_type";


export default __t.row({
  id: __t.string().primaryKey().name("Id"),
  worldId: __t.string().name("WorldId"),
  positionX: __t.i32().name("PositionX"),
  positionY: __t.i32().name("PositionY"),
  get type() {
    return TerrainDetailType.name("Type");
  },
  health: __t.option(__t.i32()).name("Health"),
  label: __t.option(__t.string()).name("Label"),
  rotation: __t.i32().name("Rotation"),
  get renderOffset() {
    return Vector2Float.name("RenderOffset");
  },
});
