// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import TerrainDetailType from "./terrain_detail_type_type";


export default __t.row({
  id: __t.string().primaryKey(),
  worldId: __t.string(),
  positionX: __t.f32(),
  positionY: __t.f32(),
  gridX: __t.i32(),
  gridY: __t.i32(),
  get type() {
    return TerrainDetailType;
  },
  health: __t.option(__t.i32()),
  label: __t.option(__t.string()),
  rotation: __t.i32(),
  width: __t.option(__t.i32()),
  height: __t.option(__t.i32()),
});
