// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

const TerrainDetailType = __t.enum("TerrainDetailType", {None: __t.unit(),
  Cliff: __t.unit(),
  Rock: __t.unit(),
  Tree: __t.unit(),
  Bridge: __t.unit(),
  Fence: __t.unit(),
  HayBale: __t.unit(),
  Field: __t.unit(),
  Label: __t.unit(),
  TripleShooterPickup: __t.unit(),
  MissileLauncherPickup: __t.unit(),
  HealthPickup: __t.unit(),
});

export default TerrainDetailType;


