// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import ScheduledGameActivityCheck from "./scheduled_game_activity_check_type";

export default {
<<<<<<<< HEAD:frontend/module_bindings/tutorial_skip_reducer.ts
  gameId: __t.string(),
  joinCode: __t.string(),
========
  get args() {
    return ScheduledGameActivityCheck;
  },
>>>>>>>> c7c4bbb64968429354e527424c0e2516f4634dd4:frontend/module_bindings/check_game_activity_reducer.ts
};
