// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

// The tagged union or sum type for the algebraic type `AiBehavior`.
export const AiBehavior = __t.enum("AiBehavior", {
  None: __t.unit(),
  GameAi: __t.unit(),
});
export type AiBehavior = __Infer<typeof AiBehavior>;

export const AiConfig = __t.object("AiConfig", {
  penMinX: __t.i32(),
  penMaxX: __t.i32(),
  penMinY: __t.i32(),
  penMaxY: __t.i32(),
});
export type AiConfig = __Infer<typeof AiConfig>;

// The tagged union or sum type for the algebraic type `BaseTerrain`.
export const BaseTerrain = __t.enum("BaseTerrain", {
  Ground: __t.unit(),
  Farm: __t.unit(),
  BlackChecker: __t.unit(),
  WhiteChecker: __t.unit(),
  Water: __t.unit(),
});
export type BaseTerrain = __Infer<typeof BaseTerrain>;

export const BaseTerrainLayer = __t.object("BaseTerrainLayer", {
  gameId: __t.string(),
  get layer() {
    return __t.array(BaseTerrain);
  },
  width: __t.i32(),
  height: __t.i32(),
});
export type BaseTerrainLayer = __Infer<typeof BaseTerrainLayer>;

export const DailyActiveUsers = __t.object("DailyActiveUsers", {
  day: __t.string(),
  totalCount: __t.i32(),
  newCount: __t.i32(),
});
export type DailyActiveUsers = __Infer<typeof DailyActiveUsers>;

export const DamagedTank = __t.object("DamagedTank", {
  tankId: __t.string(),
  damagedAt: __t.u64(),
});
export type DamagedTank = __Infer<typeof DamagedTank>;

export const DamagedTile = __t.object("DamagedTile", {
  x: __t.i32(),
  y: __t.i32(),
  damagedAt: __t.u64(),
});
export type DamagedTile = __Infer<typeof DamagedTile>;

export const Destination = __t.object("Destination", {
  id: __t.string(),
  gameId: __t.string(),
  targetCode: __t.string(),
  get type() {
    return DestinationType;
  },
  positionX: __t.f32(),
  positionY: __t.f32(),
  gridX: __t.i32(),
  gridY: __t.i32(),
});
export type Destination = __Infer<typeof Destination>;

// The tagged union or sum type for the algebraic type `DestinationType`.
export const DestinationType = __t.enum("DestinationType", {
  Pickup: __t.unit(),
  Anchor: __t.unit(),
});
export type DestinationType = __Infer<typeof DestinationType>;

// The tagged union or sum type for the algebraic type `ExplosionTrigger`.
export const ExplosionTrigger = __t.enum("ExplosionTrigger", {
  None: __t.unit(),
  OnExpiration: __t.unit(),
  OnHit: __t.unit(),
});
export type ExplosionTrigger = __Infer<typeof ExplosionTrigger>;

export const Game = __t.object("Game", {
  id: __t.string(),
  createdAt: __t.u64(),
  width: __t.i32(),
  height: __t.i32(),
  get gameState() {
    return GameState;
  },
  get gameType() {
    return GameType;
  },
  gameStartedAt: __t.u64(),
  gameDurationMicros: __t.i64(),
  get visibility() {
    return GameVisibility;
  },
  maxPlayers: __t.i32(),
  currentPlayerCount: __t.i32(),
  botCount: __t.i32(),
  minPlayersPerTeam: __t.i32(),
  owner: __t.option(__t.identity()),
});
export type Game = __Infer<typeof Game>;

export const GameRedirect = __t.object("GameRedirect", {
  oldGameId: __t.string(),
  newGameId: __t.string(),
  insertedAt: __t.u64(),
});
export type GameRedirect = __Infer<typeof GameRedirect>;

// The tagged union or sum type for the algebraic type `GameState`.
export const GameState = __t.enum("GameState", {
  Playing: __t.unit(),
  Results: __t.unit(),
});
export type GameState = __Infer<typeof GameState>;

// The tagged union or sum type for the algebraic type `GameType`.
export const GameType = __t.enum("GameType", {
  Game: __t.unit(),
  Home: __t.unit(),
  Tutorial: __t.unit(),
});
export type GameType = __Infer<typeof GameType>;

// The tagged union or sum type for the algebraic type `GameVisibility`.
export const GameVisibility = __t.enum("GameVisibility", {
  Public: __t.unit(),
  Private: __t.unit(),
  CustomPublic: __t.unit(),
});
export type GameVisibility = __Infer<typeof GameVisibility>;

export const Gun = __t.object("Gun", {
  get gunType() {
    return GunType;
  },
  ammo: __t.option(__t.i32()),
  projectileCount: __t.i32(),
  spreadAngle: __t.f32(),
  damage: __t.i32(),
  trackingStrength: __t.f32(),
  trackingRadius: __t.f32(),
  get projectileType() {
    return ProjectileType;
  },
  lifetimeSeconds: __t.f32(),
  maxCollisions: __t.i32(),
  passThroughTerrain: __t.bool(),
  collisionRadius: __t.f32(),
  explosionRadius: __t.option(__t.f32()),
  get explosionTrigger() {
    return ExplosionTrigger;
  },
  damping: __t.option(__t.f32()),
  bounce: __t.bool(),
  projectileSize: __t.f32(),
  projectileSpeed: __t.f32(),
});
export type Gun = __Infer<typeof Gun>;

// The tagged union or sum type for the algebraic type `GunType`.
export const GunType = __t.enum("GunType", {
  Base: __t.unit(),
  TripleShooter: __t.unit(),
  MissileLauncher: __t.unit(),
  Boomerang: __t.unit(),
  Grenade: __t.unit(),
  Rocket: __t.unit(),
  Moag: __t.unit(),
  Sniper: __t.unit(),
});
export type GunType = __Infer<typeof GunType>;

export const Kill = __t.object("Kill", {
  id: __t.string(),
  gameId: __t.string(),
  killer: __t.identity(),
  killeeName: __t.string(),
  killeeIsBot: __t.bool(),
  timestamp: __t.u64(),
});
export type Kill = __Infer<typeof Kill>;

export const Message = __t.object("Message", {
  id: __t.string(),
  gameId: __t.string(),
  sender: __t.string(),
  senderIdentity: __t.option(__t.identity()),
  text: __t.string(),
  timestamp: __t.u64(),
});
export type Message = __Infer<typeof Message>;

export const Pickup = __t.object("Pickup", {
  id: __t.string(),
  gameId: __t.string(),
  positionX: __t.f32(),
  positionY: __t.f32(),
  gridX: __t.i32(),
  gridY: __t.i32(),
  get type() {
    return PickupType;
  },
  ammo: __t.option(__t.i32()),
});
export type Pickup = __Infer<typeof Pickup>;

// The tagged union or sum type for the algebraic type `PickupType`.
export const PickupType = __t.enum("PickupType", {
  TripleShooter: __t.unit(),
  MissileLauncher: __t.unit(),
  Health: __t.unit(),
  Boomerang: __t.unit(),
  Grenade: __t.unit(),
  Rocket: __t.unit(),
  Moag: __t.unit(),
  Shield: __t.unit(),
  Sniper: __t.unit(),
});
export type PickupType = __Infer<typeof PickupType>;

export const Player = __t.object("Player", {
  id: __t.string(),
  identity: __t.identity(),
  name: __t.option(__t.string()),
  createdAt: __t.u64(),
  tutorialComplete: __t.bool(),
  lastGameJoinedDay: __t.option(__t.string()),
});
export type Player = __Infer<typeof Player>;

export const Projectile = __t.object("Projectile", {
  id: __t.u64(),
  gameId: __t.string(),
  shooterTankId: __t.string(),
  alliance: __t.i32(),
  size: __t.f32(),
  damage: __t.i32(),
  trackingStrength: __t.f32(),
  trackingRadius: __t.f32(),
  get projectileType() {
    return ProjectileType;
  },
  spawnedAt: __t.u64(),
  lifetimeSeconds: __t.f32(),
  returnsToShooter: __t.bool(),
  maxCollisions: __t.i32(),
  passThroughTerrain: __t.bool(),
  collisionRadius: __t.f32(),
  explosionRadius: __t.option(__t.f32()),
  get explosionTrigger() {
    return ExplosionTrigger;
  },
  damping: __t.option(__t.f32()),
  bounce: __t.bool(),
  speed: __t.f32(),
  isReturning: __t.bool(),
  recentlyDamagedTiles: __t.option(__t.array(DamagedTile)),
  recentlyHitTanks: __t.option(__t.array(DamagedTank)),
});
export type Projectile = __Infer<typeof Projectile>;

export const ProjectileTransform = __t.object("ProjectileTransform", {
  projectileId: __t.u64(),
  gameId: __t.string(),
  positionX: __t.f32(),
  positionY: __t.f32(),
  get velocity() {
    return Vector2Float;
  },
  collisionCount: __t.i32(),
});
export type ProjectileTransform = __Infer<typeof ProjectileTransform>;

export const ProjectileTraversibilityMap = __t.object("ProjectileTraversibilityMap", {
  gameId: __t.string(),
  map: __t.byteArray(),
  width: __t.i32(),
  height: __t.i32(),
  version: __t.u64(),
});
export type ProjectileTraversibilityMap = __Infer<typeof ProjectileTraversibilityMap>;

// The tagged union or sum type for the algebraic type `ProjectileType`.
export const ProjectileType = __t.enum("ProjectileType", {
  Normal: __t.unit(),
  Missile: __t.unit(),
  Boomerang: __t.unit(),
  Grenade: __t.unit(),
  Rocket: __t.unit(),
  Moag: __t.unit(),
  Sniper: __t.unit(),
});
export type ProjectileType = __Infer<typeof ProjectileType>;

export const ScheduledEnemyTankRespawnCheck = __t.object("ScheduledEnemyTankRespawnCheck", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  gameId: __t.string(),
});
export type ScheduledEnemyTankRespawnCheck = __Infer<typeof ScheduledEnemyTankRespawnCheck>;

export const ScheduledGameActivityCheck = __t.object("ScheduledGameActivityCheck", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type ScheduledGameActivityCheck = __Infer<typeof ScheduledGameActivityCheck>;

export const ScheduledGameCleanup = __t.object("ScheduledGameCleanup", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type ScheduledGameCleanup = __Infer<typeof ScheduledGameCleanup>;

export const ScheduledGameEnd = __t.object("ScheduledGameEnd", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  gameId: __t.string(),
});
export type ScheduledGameEnd = __Infer<typeof ScheduledGameEnd>;

export const ScheduledGameReset = __t.object("ScheduledGameReset", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  gameId: __t.string(),
});
export type ScheduledGameReset = __Infer<typeof ScheduledGameReset>;

export const ScheduledPickupSpawn = __t.object("ScheduledPickupSpawn", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  gameId: __t.string(),
});
export type ScheduledPickupSpawn = __Infer<typeof ScheduledPickupSpawn>;

export const ScheduledProjectileUpdates = __t.object("ScheduledProjectileUpdates", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  gameId: __t.string(),
  lastTickAt: __t.u64(),
  tickCount: __t.u64(),
});
export type ScheduledProjectileUpdates = __Infer<typeof ScheduledProjectileUpdates>;

export const ScheduledTankAiUpdate = __t.object("ScheduledTankAiUpdate", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  gameId: __t.string(),
  tickCount: __t.u64(),
});
export type ScheduledTankAiUpdate = __Infer<typeof ScheduledTankAiUpdate>;

export const ScheduledTankUpdates = __t.object("ScheduledTankUpdates", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  gameId: __t.string(),
  lastTickAt: __t.u64(),
  tickCount: __t.u64(),
});
export type ScheduledTankUpdates = __Infer<typeof ScheduledTankUpdates>;

export const Score = __t.object("Score", {
  gameId: __t.string(),
  kills: __t.array(__t.i32()),
});
export type Score = __Infer<typeof Score>;

export const Tank = __t.object("Tank", {
  id: __t.string(),
  gameId: __t.string(),
  owner: __t.identity(),
  name: __t.string(),
  targetCode: __t.string(),
  joinCode: __t.option(__t.string()),
  isBot: __t.bool(),
  get aiBehavior() {
    return AiBehavior;
  },
  get aiConfig() {
    return __t.option(AiConfig);
  },
  alliance: __t.i32(),
  maxHealth: __t.i32(),
  topSpeed: __t.f32(),
  turretRotationSpeed: __t.f32(),
  health: __t.i32(),
  kills: __t.i32(),
  deaths: __t.i32(),
  killStreak: __t.i32(),
  target: __t.option(__t.string()),
  targetLead: __t.f32(),
  message: __t.option(__t.string()),
  selectedGunIndex: __t.i32(),
  hasShield: __t.bool(),
  remainingImmunityMicros: __t.i64(),
  deathTimestamp: __t.u64(),
  lastDamagedBy: __t.option(__t.identity()),
});
export type Tank = __Infer<typeof Tank>;

export const TankFireState = __t.object("TankFireState", {
  tankId: __t.string(),
  gameId: __t.string(),
  lastFireTime: __t.u64(),
  get gunType() {
    return GunType;
  },
});
export type TankFireState = __Infer<typeof TankFireState>;

export const TankGun = __t.object("TankGun", {
  id: __t.u64(),
  tankId: __t.string(),
  gameId: __t.string(),
  slotIndex: __t.i32(),
  get gun() {
    return Gun;
  },
});
export type TankGun = __Infer<typeof TankGun>;

export const TankPath = __t.object("TankPath", {
  tankId: __t.string(),
  gameId: __t.string(),
  owner: __t.identity(),
  get path() {
    return __t.array(Vector2Float);
  },
  pathIndex: __t.i32(),
});
export type TankPath = __Infer<typeof TankPath>;

export const TankTransform = __t.object("TankTransform", {
  tankId: __t.string(),
  gameId: __t.string(),
  positionX: __t.f32(),
  positionY: __t.f32(),
  get velocity() {
    return Vector2Float;
  },
  collisionRegionX: __t.i32(),
  collisionRegionY: __t.i32(),
  turretRotation: __t.f32(),
  targetTurretRotation: __t.f32(),
  turretAngularVelocity: __t.f32(),
  updatedAt: __t.u64(),
});
export type TankTransform = __Infer<typeof TankTransform>;

export const TerrainDetail = __t.object("TerrainDetail", {
  id: __t.string(),
  gameId: __t.string(),
  positionX: __t.f32(),
  positionY: __t.f32(),
  gridX: __t.i32(),
  gridY: __t.i32(),
  get type() {
    return TerrainDetailType;
  },
  health: __t.option(__t.i32()),
  label: __t.option(__t.string()),
  rotation: __t.i32(),
});
export type TerrainDetail = __Infer<typeof TerrainDetail>;

// The tagged union or sum type for the algebraic type `TerrainDetailType`.
export const TerrainDetailType = __t.enum("TerrainDetailType", {
  None: __t.unit(),
  Rock: __t.unit(),
  Tree: __t.unit(),
  HayBale: __t.unit(),
  Label: __t.unit(),
  FoundationEdge: __t.unit(),
  FoundationCorner: __t.unit(),
  FenceEdge: __t.unit(),
  FenceCorner: __t.unit(),
  TargetDummy: __t.unit(),
  DeadTree: __t.unit(),
  PenBorder: __t.unit(),
});
export type TerrainDetailType = __Infer<typeof TerrainDetailType>;

export const TraversibilityMap = __t.object("TraversibilityMap", {
  gameId: __t.string(),
  map: __t.byteArray(),
  width: __t.i32(),
  height: __t.i32(),
  version: __t.u64(),
});
export type TraversibilityMap = __Infer<typeof TraversibilityMap>;

export const Vector2Float = __t.object("Vector2Float", {
  x: __t.f32(),
  y: __t.f32(),
});
export type Vector2Float = __Infer<typeof Vector2Float>;

