// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import BaseTerrain from "./base_terrain_type";
import GameState from "./game_state_type";


export default __t.object("World", {
  id: __t.string(),
  name: __t.string(),
  createdAt: __t.u64(),
  width: __t.i32(),
  height: __t.i32(),
  get baseTerrainLayer() {
    return __t.array(BaseTerrain);
  },
  get gameState() {
    return GameState;
  },
  gameStartedAt: __t.u64(),
});


