// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AimReducer from "../aim_reducer";
import ChangeNameReducer from "../change_name_reducer";
import CreateGameReducer from "../create_game_reducer";
import DeleteKillReducer from "../delete_kill_reducer";
import DriveReducer from "../drive_reducer";
import EnsureHomegameReducer from "../ensure_homegame_reducer";
import EnsureTutorialReducer from "../ensure_tutorial_reducer";
import ExitGameReducer from "../exit_game_reducer";
import FireReducer from "../fire_reducer";
import JoinGameReducer from "../join_game_reducer";
import RespawnReducer from "../respawn_reducer";
import SayReducer from "../say_reducer";
import StopReducer from "../stop_reducer";
import SwitchGunReducer from "../switch_gun_reducer";
import TrackReducer from "../track_reducer";
import TutorialCompleteReducer from "../tutorial_complete_reducer";
import TutorialSkipReducer from "../tutorial_skip_reducer";

export type AimParams = __Infer<typeof AimReducer>;
export type ChangeNameParams = __Infer<typeof ChangeNameReducer>;
export type CreateGameParams = __Infer<typeof CreateGameReducer>;
export type DeleteKillParams = __Infer<typeof DeleteKillReducer>;
export type DriveParams = __Infer<typeof DriveReducer>;
export type EnsureHomegameParams = __Infer<typeof EnsureHomegameReducer>;
export type EnsureTutorialParams = __Infer<typeof EnsureTutorialReducer>;
export type ExitGameParams = __Infer<typeof ExitGameReducer>;
export type FireParams = __Infer<typeof FireReducer>;
export type JoinGameParams = __Infer<typeof JoinGameReducer>;
export type RespawnParams = __Infer<typeof RespawnReducer>;
export type SayParams = __Infer<typeof SayReducer>;
export type StopParams = __Infer<typeof StopReducer>;
export type SwitchGunParams = __Infer<typeof SwitchGunReducer>;
export type TrackParams = __Infer<typeof TrackReducer>;
export type TutorialCompleteParams = __Infer<typeof TutorialCompleteReducer>;
export type TutorialSkipParams = __Infer<typeof TutorialSkipReducer>;

