import { COLORS } from "./theme/colors";

export const UNIT_TO_PIXEL = 50;

export const GUN_BARREL_LENGTH = 0.4;

export const INTERPOLATION_DELAY = 100;
export const BUFFER_DURATION = 200;

export const TERRAIN_DETAIL_RADIUS = {
  ROCK: 0.38,
  TREE: 0.648,
  HAY_BALE: 0.35,
};

export const TEAM_COLORS = {
  RED: COLORS.GAME.TEAM_RED_BRIGHT,
  BLUE: COLORS.GAME.TEAM_BLUE_BRIGHT,
};

export const TERRAIN_COLORS = {
  GROUND: COLORS.TERRAIN.GROUND,
  FARM_GROOVE: COLORS.TERRAIN.FARM_GROOVE,
  GRID: COLORS.TERRAIN.GRID,
  CHECKER: COLORS.TERRAIN.CHECKER,
};

export const TERRAIN_DETAIL_COLORS = {
  TREE: {
    BASE: COLORS.TERRAIN.TREE_BASE,
    FOLIAGE: COLORS.TERRAIN.TREE_FOLIAGE,
  },
  DEAD_TREE: {
    BASE: COLORS.TERRAIN.DEAD_TREE_BASE,
    FOLIAGE: COLORS.TERRAIN.DEAD_TREE_FOLIAGE,
  },
  ROCK: {
    BODY: COLORS.TERRAIN.ROCK_BODY,
    SHADOW: COLORS.TERRAIN.ROCK_SHADOW,
    HIGHLIGHT: COLORS.TERRAIN.ROCK_HIGHLIGHT,
    OUTLINE: COLORS.TERRAIN.ROCK_OUTLINE,
  },
  HAY_BALE: {
    BODY: COLORS.TERRAIN.HAY_BALE_BODY,
    RING: COLORS.TERRAIN.HAY_BALE_RING,
  },
  FOUNDATION: {
    BASE: COLORS.TERRAIN.FOUNDATION_BASE,
  },
  FENCE: {
    RAIL: COLORS.TERRAIN.FENCE_RAIL,
    POST: COLORS.TERRAIN.FENCE_POST,
  },
  TARGET_DUMMY: {
    BODY: COLORS.TERRAIN.TARGET_DUMMY_BODY,
    RIM: COLORS.TERRAIN.TARGET_DUMMY_RIM,
    CENTER: COLORS.TERRAIN.TARGET_DUMMY_CENTER,
  },
};

export const DECORATION_COLORS = {
  MUSHROOM: {
    CAP: COLORS.TERRAIN.MUSHROOM_CAP,
    SHADOW: COLORS.TERRAIN.MUSHROOM_SHADOW,
  },
};

export const UI_COLORS = {
  TEXT_BRIGHT: COLORS.UI.TEXT_PRIMARY,
  BACKGROUND_DARK: COLORS.UI.BACKGROUND_DARK,
  WHITE: COLORS.UI.WHITE,
  BLACK: COLORS.UI.BLACK,
  TEAM_RED_DARK: COLORS.UI.TEAM_RED_DARK,
  TEAM_BLUE_DARK: COLORS.UI.TEAM_BLUE_DARK,
  TEAM_RED_MEDIUM: COLORS.UI.TEAM_RED_MEDIUM,
  TEAM_BLUE_MEDIUM: COLORS.UI.TEAM_BLUE_MEDIUM,
  LABEL_YELLOW: COLORS.UI.LABEL_YELLOW,
};

export const ABILITY_COLORS = {
  OVERDRIVE_READY: COLORS.ABILITY.OVERDRIVE_READY,
  COOLDOWN_GRAY: COLORS.ABILITY.COOLDOWN,
};

export const PICKUP_COLORS = {
  HEALTH_PACK_SECONDARY: COLORS.GAME.HEALTH_PACK_SECONDARY,
  SHIELD_STROKE: COLORS.GAME.SHIELD_STROKE,
};

export const PROJECTILE_COLORS = {
  OUTLINE_DARK: COLORS.GAME.PROJECTILE_OUTLINE,
  METAL_GRAY: COLORS.GAME.PROJECTILE_METAL,
};

export const EFFECT_COLORS = {
  FIRE_RED: COLORS.EFFECTS.FIRE_RED,
  FIRE_ORANGE: COLORS.EFFECTS.FIRE_ORANGE,
  FIRE_YELLOW: COLORS.EFFECTS.FIRE_YELLOW,
  FIRE_BRIGHT: COLORS.EFFECTS.FIRE_BRIGHT,
};

