const PALETTE = {
  WHITE_BRIGHT: "#fcfbf3",
  WHITE_PURE: "#ffffff",
  BLACK_PURE: "#000000",
  
  SLATE_DARKEST: "#2a152d",
  SLATE_DARK: "#34404f",
  SLATE_MEDIUM: "#4a4b5b",
  SLATE_LIGHT: "#707b89",
  SLATE_LIGHTER: "#a9bcbf",
  SLATE_LIGHTEST: "#e6eeed",
  
  RED_BRIGHT: "#ff5555",
  RED_DARK: "#813645",
  RED_MEDIUM: "#9d4343",
  RED_MUTED: "#c06852",
  
  BLUE_BRIGHT: "#5555ff",
  BLUE_DARK: "#3e4c7e",
  BLUE_MEDIUM: "#495f94",
  BLUE_LIGHT: "#5a78b2",
  BLUE_INFO: "#7396d5",
  BLUE_CYAN: "#7fbbdc",
  BLUE_CYAN_LIGHT: "#aaeeea",
  
  GREEN_SUCCESS: "#96dc7f",
  GREEN_HEALTH: "#6ec077",
  GREEN_LIME: "#d5f893",
  
  YELLOW_BRIGHT: "#fceba8",
  YELLOW_MEDIUM: "#f5c47c",
  
  ORANGE_MEDIUM: "#e39764",
  
  PURPLE_DARK: "#542240",
  PURPLE_MEDIUM: "#794e6d",
  
  GROUND_DARK: "#2e2e43",
  GROUND_MEDIUM: "#313148",
  GROUND_SHADOW: "#3e3f4d",
  GROUND_HIGHLIGHT: "#565769",
  
  TRANSPARENT_DARK: "#00000006",
  TRANSPARENT_GRID: "#4a4b5b22",
  TRANSPARENT_SHADOW: "#00000044",
  
  BLACK_10: "#0000001a",
  BLACK_20: "#00000033",
  BLACK_25: "#00000040",
  BLACK_30: "#0000004d",
  BLACK_35: "#00000059",
  BLACK_40: "#00000066",
  BLACK_50: "#00000080",
  BLACK_60: "#00000099",
  BLACK_80: "#000000cc",
  
  WHITE_10: "#ffffff1a",
  WHITE_20: "#ffffff33",
  WHITE_30: "#ffffff4d",
  
  GROUND_DARK_80: "#2e2e43cc",
  GROUND_DARK_85: "#2e2e43d9",
  GROUND_DARK_95: "#2e2e43f2",
  
  SLATE_DARKEST_60: "#2a152d99",
  SLATE_DARKEST_80: "#2a152dcc",
  SLATE_DARKEST_90: "#2a152de6",
  
  SLATE_MEDIUM_20: "#4a4b5b33",
  SLATE_MEDIUM_30: "#4a4b5b4d",
  
  SLATE_LIGHT_20: "#707b8933",
  SLATE_LIGHT_30: "#707b8940",
  SLATE_LIGHT_40: "#707b8966",
  SLATE_LIGHT_80: "#707b89cc",
  
  SLATE_LIGHTER_10: "#a9bcbf1a",
  
  RED_DARK_60: "#81364599",
  RED_DARK_80: "#813645cc",
  
  RED_MUTED_40: "#c0685266",
  RED_MUTED_60: "#c0685299",
  
  RED_MEDIUM_80: "#9d4343cc",
  
  BLUE_LIGHT_30: "#5a78b24d",
  BLUE_LIGHT_60: "#5a78b299",
  BLUE_LIGHT_80: "#5a78b2cc",
  
  BLUE_INFO_25: "#7396d540",
  BLUE_INFO_50: "#7396d580",
  
  GREEN_SUCCESS_30: "#96dc7f4d",
  GREEN_SUCCESS_50: "#96dc7f80",
  
  YELLOW_BRIGHT_10: "#fceba81a",
  YELLOW_BRIGHT_15: "#fceba826",
  
  GREEN_LIME_40: "#d5f89366",
  
  RED_DEBUG: "#ff000033",
  GREEN_DEBUG: "#00ff00cc",
} as const;

export const COLORS = {
  UI: {
    TEXT_PRIMARY: PALETTE.WHITE_BRIGHT,
    TEXT_SECONDARY: PALETTE.SLATE_LIGHTEST,
    TEXT_MUTED: PALETTE.SLATE_LIGHTER,
    TEXT_DIM: PALETTE.SLATE_LIGHT,
    
    BACKGROUND_DARK: PALETTE.SLATE_DARK,
    BACKGROUND_DARKEST: PALETTE.SLATE_DARKEST,
    
    WHITE: PALETTE.WHITE_PURE,
    BLACK: PALETTE.BLACK_PURE,
    
    TEAM_RED_DARK: PALETTE.RED_DARK,
    TEAM_RED_MEDIUM: PALETTE.RED_MEDIUM,
    TEAM_BLUE_DARK: PALETTE.BLUE_DARK,
    TEAM_BLUE_MEDIUM: PALETTE.BLUE_MEDIUM,
    
    LABEL_YELLOW: PALETTE.YELLOW_MEDIUM,
    
    SEPARATOR: PALETTE.SLATE_MEDIUM,
    
    OVERLAY_BG: PALETTE.GROUND_DARK_85,
    OVERLAY_BG_OPAQUE: PALETTE.GROUND_DARK_95,
    OVERLAY_BG_MEDIUM: PALETTE.GROUND_DARK_80,
    
    MODAL_BG: PALETTE.SLATE_DARKEST_60,
    MODAL_BG_HOVER: PALETTE.SLATE_DARKEST_80,
    MODAL_BG_FOCUS: PALETTE.SLATE_DARKEST_90,
    
    BORDER_LIGHT: PALETTE.WHITE_10,
    BORDER_MEDIUM: PALETTE.SLATE_LIGHT_30,
    BORDER_SEPARATOR: PALETTE.SLATE_LIGHT_20,
    BORDER_HOVER: PALETTE.BLUE_LIGHT_60,
    BORDER_SUCCESS: PALETTE.GREEN_SUCCESS_50,
    
    SHADOW_LIGHT: PALETTE.BLACK_40,
    SHADOW_MEDIUM: PALETTE.BLACK_50,
    
    TEXT_SHADOW_LIGHT: PALETTE.BLACK_50,
    TEXT_SHADOW_INFO: PALETTE.BLUE_INFO_50,
    TEXT_SHADOW_ERROR: PALETTE.RED_MUTED_60,
    
    CODE_BG: PALETTE.YELLOW_BRIGHT_15,
    
    TEAM_INDICATOR_RED: PALETTE.RED_MEDIUM_80,
    TEAM_INDICATOR_BLUE: PALETTE.BLUE_LIGHT_80,
    TEAM_INDICATOR_SPECTATOR: PALETTE.SLATE_LIGHT_80,
    
    BUTTON_DANGER_BG: PALETTE.RED_DARK_60,
    BUTTON_DANGER_BORDER: PALETTE.RED_MUTED_40,
    BUTTON_DANGER_HOVER_BG: PALETTE.RED_DARK_80,
    BUTTON_DANGER_HOVER_BORDER: PALETTE.RED_MUTED_60,
    
    BUTTON_SUCCESS_HOVER_BG: PALETTE.GREEN_LIME_40,
    
    SELECTION_BG: PALETTE.GREEN_SUCCESS_30,
    
    DROP_SHADOW: PALETTE.BLACK_50,
    CARD_SHADOW: PALETTE.BLACK_40,
    
    SEPARATOR_LIGHT: PALETTE.SLATE_LIGHTER_10,
  },
  
  GAME: {
    TEAM_RED_BRIGHT: PALETTE.RED_BRIGHT,
    TEAM_BLUE_BRIGHT: PALETTE.BLUE_BRIGHT,
    
    HEALTH_PACK_PRIMARY: PALETTE.GREEN_SUCCESS,
    HEALTH_PACK_SECONDARY: PALETTE.GREEN_HEALTH,
    
    SHIELD_PRIMARY: PALETTE.BLUE_INFO,
    SHIELD_SECONDARY: PALETTE.BLUE_LIGHT,
    SHIELD_STROKE: PALETTE.BLUE_MEDIUM,
    SHIELD_OVERLAY: PALETTE.BLUE_INFO_25,
    
    PROJECTILE_OUTLINE: PALETTE.GROUND_DARK,
    PROJECTILE_METAL: PALETTE.SLATE_LIGHT,
    
    SHADOW_LIGHT: PALETTE.BLACK_30,
    SHADOW_MEDIUM: PALETTE.BLACK_35,
    SHADOW_DARK: PALETTE.BLACK_50,
    
    OUTLINE_STROKE: PALETTE.BLACK_80,
    OUTLINE_LIGHT: PALETTE.BLACK_60,
    OUTLINE_FENCE: PALETTE.BLACK_25,
    
    DEBUG_COLLISION: PALETTE.RED_DEBUG,
    DEBUG_REGION: PALETTE.GREEN_DEBUG,
  },
  
  ABILITY: {
    OVERDRIVE_READY: PALETTE.YELLOW_MEDIUM,
    REPAIR_READY: PALETTE.GREEN_SUCCESS,
    SMOKESCREEN_READY: PALETTE.BLUE_CYAN_LIGHT,
    SMOKESCREEN_READY_BG: PALETTE.BLUE_LIGHT_30,
    COOLDOWN: PALETTE.SLATE_LIGHT,
    COOLDOWN_BG: PALETTE.SLATE_LIGHT_40,
    COOLDOWN_NOT_READY: PALETTE.SLATE_LIGHT_30,
    NAME_BG: PALETTE.YELLOW_BRIGHT_10,
  },
  
  TERRAIN: {
    GROUND: PALETTE.GROUND_DARK,
    FARM_GROOVE: PALETTE.GROUND_MEDIUM,
    GRID: PALETTE.TRANSPARENT_GRID,
    CHECKER: PALETTE.TRANSPARENT_DARK,
    
    TREE_BASE: PALETTE.BLUE_DARK,
    TREE_FOLIAGE: PALETTE.BLUE_MEDIUM,
    
    DEAD_TREE_BASE: PALETTE.PURPLE_DARK,
    DEAD_TREE_FOLIAGE: PALETTE.PURPLE_MEDIUM,
    
    ROCK_BODY: PALETTE.SLATE_MEDIUM,
    ROCK_SHADOW: PALETTE.GROUND_SHADOW,
    ROCK_HIGHLIGHT: PALETTE.GROUND_HIGHLIGHT,
    ROCK_OUTLINE: PALETTE.GROUND_DARK,
    
    HAY_BALE_BODY: PALETTE.YELLOW_MEDIUM,
    HAY_BALE_RING: PALETTE.ORANGE_MEDIUM,
    
    FOUNDATION_BASE: PALETTE.SLATE_LIGHT,
    
    FENCE_RAIL: PALETTE.ORANGE_MEDIUM,
    FENCE_POST: PALETTE.RED_MUTED,
    
    TARGET_DUMMY_BODY: PALETTE.RED_DARK,
    TARGET_DUMMY_RIM: PALETTE.RED_MUTED,
    TARGET_DUMMY_CENTER: PALETTE.YELLOW_MEDIUM,
    
    MUSHROOM_CAP: PALETTE.PURPLE_DARK,
    MUSHROOM_SHADOW: PALETTE.TRANSPARENT_SHADOW,
  },
  
  TERMINAL: {
    BACKGROUND: PALETTE.SLATE_DARKEST,
    BORDER: PALETTE.BLUE_LIGHT,
    
    TEXT_DEFAULT: PALETTE.SLATE_LIGHTEST,
    TEXT_MUTED: PALETTE.SLATE_LIGHTER,
    TEXT_DIM: PALETTE.SLATE_LIGHT,
    
    PROMPT: PALETTE.GREEN_SUCCESS,
    
    SUCCESS: PALETTE.GREEN_SUCCESS,
    INFO: PALETTE.BLUE_INFO,
    WARNING: PALETTE.YELLOW_BRIGHT,
    ERROR: PALETTE.RED_MUTED,
    
    COMMAND: PALETTE.BLUE_CYAN,
    ARGUMENT: PALETTE.GREEN_LIME,
    VALUE: PALETTE.YELLOW_BRIGHT,
    
    DIRECTION_SYMBOL: PALETTE.BLUE_INFO,
    TANK_CODE: PALETTE.BLUE_CYAN_LIGHT,
    
    COOLDOWN: PALETTE.ORANGE_MEDIUM,
    HEALTH: PALETTE.RED_MEDIUM,
    
    HEADER_TEXT: PALETTE.SLATE_LIGHTEST,
    SEPARATOR: PALETTE.SLATE_MEDIUM,
  },
  
  EFFECTS: {
    FIRE_RED: PALETTE.RED_MUTED,
    FIRE_ORANGE: PALETTE.ORANGE_MEDIUM,
    FIRE_YELLOW: PALETTE.YELLOW_MEDIUM,
    FIRE_BRIGHT: PALETTE.YELLOW_BRIGHT,
  },
  
  MINIMAP: {
    BORDER: PALETTE.WHITE_20,
  },
} as const;

function hexToRgb(hex: string): { r: number; g: number; b: number } {
  const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
  return result
    ? {
        r: parseInt(result[1], 16),
        g: parseInt(result[2], 16),
        b: parseInt(result[3], 16),
      }
    : { r: 255, g: 255, b: 255 };
}

function colorToAnsi(hex: string): string {
  const rgb = hexToRgb(hex);
  return `\x1b[38;2;${rgb.r};${rgb.g};${rgb.b}m`;
}

const ANSI_RESET = "\x1b[0m";

export type TerminalColorKey = keyof typeof COLORS.TERMINAL;

export function colorize(text: string, colorKey: TerminalColorKey): string {
  const color = COLORS.TERMINAL[colorKey];
  const ansiColor = colorToAnsi(color);
  return `${ansiColor}${text}${ANSI_RESET}`;
}

export function success(text: string): string {
  return colorize(text, 'SUCCESS');
}

export function info(text: string): string {
  return colorize(text, 'INFO');
}

export function warning(text: string): string {
  return colorize(text, 'WARNING');
}

export function error(text: string): string {
  return colorize(text, 'ERROR');
}

export function command(text: string): string {
  return colorize(text, 'COMMAND');
}

export function argument(text: string): string {
  return colorize(text, 'ARGUMENT');
}

export function value(text: string): string {
  return colorize(text, 'VALUE');
}

export function muted(text: string): string {
  return colorize(text, 'TEXT_MUTED');
}

export function dim(text: string): string {
  return colorize(text, 'TEXT_DIM');
}
