export declare const PALETTE: {
  readonly WHITE_BRIGHT: string;
  readonly WHITE_PURE: string;
  readonly BLACK_PURE: string;
  readonly SLATE_DARKEST: string;
  readonly SLATE_DARK: string;
  readonly SLATE_MEDIUM: string;
  readonly SLATE_LIGHT: string;
  readonly SLATE_LIGHTER: string;
  readonly SLATE_LIGHTEST: string;
  readonly RED_BRIGHT: string;
  readonly RED_DARK: string;
  readonly RED_MEDIUM: string;
  readonly RED_MUTED: string;
  readonly BLUE_BRIGHT: string;
  readonly BLUE_DARK: string;
  readonly BLUE_MEDIUM: string;
  readonly BLUE_LIGHT: string;
  readonly BLUE_INFO: string;
  readonly BLUE_CYAN: string;
  readonly BLUE_CYAN_LIGHT: string;
  readonly GREEN_SUCCESS: string;
  readonly GREEN_HEALTH: string;
  readonly GREEN_LIME: string;
  readonly TEAL_DARK: string;
  readonly TEAL_MEDIUM: string;
  readonly YELLOW_BRIGHT: string;
  readonly YELLOW_MEDIUM: string;
  readonly ORANGE_MEDIUM: string;
  readonly PURPLE_DARK: string;
  readonly PURPLE_MEDIUM: string;
  readonly PURPLE_BRIGHT: string;
  readonly PURPLE_BRIGHT_DARK: string;
  readonly GROUND_DARK: string;
  readonly GROUND_MEDIUM: string;
  readonly GROUND_SHADOW: string;
  readonly GROUND_HIGHLIGHT: string;
  readonly TRANSPARENT_DARK: string;
  readonly TRANSPARENT_GRID: string;
  readonly TRANSPARENT_SHADOW: string;
  readonly PURPLE_VOID: string;
};

export declare const UI_COLORS: {
  readonly TEXT_PRIMARY: string;
  readonly TEXT_SECONDARY: string;
  readonly TEXT_MUTED: string;
  readonly TEXT_DIM: string;
  readonly BACKGROUND_DARK: string;
  readonly BACKGROUND_DARKEST: string;
  readonly WHITE: string;
  readonly BLACK: string;
  readonly TEAM_RED_DARK: string;
  readonly TEAM_RED_MEDIUM: string;
  readonly TEAM_BLUE_DARK: string;
  readonly TEAM_BLUE_MEDIUM: string;
  readonly LABEL_YELLOW: string;
  readonly SEPARATOR: string;
};

export declare const GAME_COLORS: {
  readonly TEAM_RED_BRIGHT: string;
  readonly TEAM_BLUE_BRIGHT: string;
  readonly HEALTH_PACK_PRIMARY: string;
  readonly HEALTH_PACK_SECONDARY: string;
  readonly SHIELD_PRIMARY: string;
  readonly SHIELD_SECONDARY: string;
  readonly SHIELD_STROKE: string;
  readonly PROJECTILE_OUTLINE: string;
  readonly PROJECTILE_METAL: string;
  readonly WEAPON_PICKUP_PRIMARY: string;
  readonly WEAPON_PICKUP_SECONDARY: string;
  readonly WEAPON_PICKUP_HIGHLIGHT: string;
};

export declare const TERMINAL_COLORS: {
  readonly BACKGROUND: string;
  readonly BORDER: string;
  readonly TEXT_DEFAULT: string;
  readonly TEXT_MUTED: string;
  readonly TEXT_DIM: string;
  readonly PROMPT: string;
  readonly SUCCESS: string;
  readonly INFO: string;
  readonly WARNING: string;
  readonly ERROR: string;
  readonly COMMAND: string;
  readonly ARGUMENT: string;
  readonly VALUE: string;
  readonly DIRECTION_SYMBOL: string;
  readonly TANK_CODE: string;
  readonly COOLDOWN: string;
  readonly HEALTH: string;
  readonly HEADER_TEXT: string;
  readonly SEPARATOR: string;
  readonly TEAM_RED: string;
  readonly TEAM_BLUE: string;
};
