export const PALETTE = {
  WHITE_BRIGHT: "#ffffff",
  WHITE_PURE: "#ffffff",
  BLACK_PURE: "#000000",

  SLATE_DARKEST: "#0a0a12",
  SLATE_DARK: "#0d0d18",
  SLATE_MEDIUM: "#151525",
  SLATE_LIGHT: "#00ffff",
  SLATE_LIGHTER: "#00ffff",
  SLATE_LIGHTEST: "#ffffff",

  RED_BRIGHT: "#ff2266",
  RED_DARK: "#330011",
  RED_MEDIUM: "#ff0044",
  RED_MUTED: "#ff4488",

  BLUE_BRIGHT: "#00ccff",
  BLUE_DARK: "#001133",
  BLUE_MEDIUM: "#0088ff",
  BLUE_LIGHT: "#00aaff",
  BLUE_INFO: "#00ddff",
  BLUE_CYAN: "#00ffff",
  BLUE_CYAN_LIGHT: "#88ffff",

  GREEN_SUCCESS: "#00ff88",
  GREEN_HEALTH: "#00ff66",
  GREEN_LIME: "#88ff00",

  YELLOW_BRIGHT: "#ffff00",
  YELLOW_MEDIUM: "#ffcc00",

  ORANGE_MEDIUM: "#ff8800",

  PURPLE_DARK: "#220033",
  PURPLE_MEDIUM: "#aa00ff",
  PURPLE_BRIGHT: "#cc66ff",
  PURPLE_BRIGHT_DARK: "#6600aa",

  GROUND_DARK: "#050508",
  GROUND_MEDIUM: "#080810",
  GROUND_SHADOW: "#000000",
  GROUND_HIGHLIGHT: "#101020",

  TRANSPARENT_DARK: "#00000000",
  TRANSPARENT_GRID: "#00ffff15",
  TRANSPARENT_SHADOW: "#00000000",

  PURPLE_VOID: "#030306",

  NEON_PINK: "#ff00aa",
  NEON_CYAN: "#00ffff",
  NEON_GREEN: "#00ff66",
  NEON_YELLOW: "#ffff00",
  NEON_ORANGE: "#ff6600",
  NEON_PURPLE: "#aa00ff",
  NEON_BLUE: "#0088ff",
  NEON_WHITE: "#ffffff",
};

export const UI_COLORS = {
  TEXT_PRIMARY: PALETTE.WHITE_PURE,
  TEXT_SECONDARY: PALETTE.NEON_CYAN,
  TEXT_MUTED: PALETTE.NEON_CYAN,
  TEXT_DIM: PALETTE.BLUE_CYAN,

  BACKGROUND_DARK: PALETTE.SLATE_DARK,
  BACKGROUND_DARKEST: PALETTE.SLATE_DARKEST,

  WHITE: PALETTE.WHITE_PURE,
  BLACK: PALETTE.BLACK_PURE,

  TEAM_RED_DARK: PALETTE.RED_DARK,
  TEAM_RED_MEDIUM: PALETTE.RED_MEDIUM,
  TEAM_BLUE_DARK: PALETTE.BLUE_DARK,
  TEAM_BLUE_MEDIUM: PALETTE.BLUE_MEDIUM,

  LABEL_YELLOW: PALETTE.NEON_YELLOW,

  SEPARATOR: PALETTE.NEON_CYAN,
};

export const GAME_COLORS = {
  TEAM_RED_BRIGHT: PALETTE.NEON_PINK,
  TEAM_BLUE_BRIGHT: PALETTE.NEON_CYAN,

  HEALTH_PACK_PRIMARY: PALETTE.NEON_GREEN,
  HEALTH_PACK_SECONDARY: PALETTE.GREEN_HEALTH,

  SHIELD_PRIMARY: PALETTE.NEON_BLUE,
  SHIELD_SECONDARY: PALETTE.BLUE_LIGHT,
  SHIELD_STROKE: PALETTE.NEON_CYAN,

  PROJECTILE_OUTLINE: PALETTE.BLACK_PURE,
  PROJECTILE_METAL: PALETTE.NEON_CYAN,

  WEAPON_PICKUP_PRIMARY: PALETTE.NEON_CYAN,
  WEAPON_PICKUP_SECONDARY: PALETTE.NEON_CYAN,
  WEAPON_PICKUP_HIGHLIGHT: PALETTE.WHITE_PURE,
};

export const TERMINAL_COLORS = {
  BACKGROUND: PALETTE.PURPLE_VOID,
  BORDER: PALETTE.NEON_CYAN,

  TEXT_DEFAULT: PALETTE.NEON_CYAN,
  TEXT_MUTED: PALETTE.BLUE_CYAN,
  TEXT_DIM: PALETTE.BLUE_MEDIUM,

  PROMPT: PALETTE.NEON_GREEN,

  SUCCESS: PALETTE.NEON_GREEN,
  INFO: PALETTE.NEON_CYAN,
  WARNING: PALETTE.NEON_YELLOW,
  ERROR: PALETTE.NEON_PINK,

  COMMAND: PALETTE.NEON_CYAN,
  ARGUMENT: PALETTE.NEON_GREEN,
  VALUE: PALETTE.NEON_YELLOW,

  DIRECTION_SYMBOL: PALETTE.NEON_BLUE,
  TANK_CODE: PALETTE.NEON_CYAN,

  COOLDOWN: PALETTE.NEON_ORANGE,
  HEALTH: PALETTE.NEON_PINK,

  HEADER_TEXT: PALETTE.WHITE_PURE,
  SEPARATOR: PALETTE.NEON_CYAN,

  TEAM_RED: PALETTE.NEON_PINK,
  TEAM_BLUE: PALETTE.NEON_CYAN,
};
